// @generated by cargo xtask ast-codegen; do not edit.
//! The one call of the variadic `clingo_ast_build`, with the C argument
//! types of every node type taken from clingo's constructor table.
//!
//! Generated by `cargo xtask ast-codegen`.
#![allow(
    clippy::too_many_lines,
    reason = "one arm per node type, generated from the table"
)]
use clingox_sys as ffi;
use super::ast::Prepared;
use super::c_int_of;
use crate::ast::AstType;
/// Builds a node of type `kind` from `args`, the C values of the arguments
/// the constructor table lists for it, in order.
///
/// `args` must have been prepared from arguments of exactly the kinds the
/// table lists (the safe constructors are generated from the same table);
/// its accessors panic otherwise, before any pointer is read.
pub(super) fn build(
    kind: AstType,
    args: &Prepared,
    out: &mut *mut ffi::clingo_ast_t,
) -> bool {
    // SAFETY: `clingo_ast_build` reads its variadic arguments in the order and
    // with the C types of the constructor table entry for `kind` (control.cc,
    // `clingo_ast_build`): `int` for a number, `clingo_symbol_t` for a symbol,
    // `const clingo_location_t *`, `const char *`, `clingo_ast_t *` (null for
    // an absent optional node), and a pointer plus a `size_t` for an array.
    // Each arm below passes exactly the table's arguments for its node type,
    // in the table's order and with those types, because this file is
    // generated from the table. Every pointer comes from `args`, which owns
    // the C strings and arrays and borrows the nodes, and outlives the call;
    // the accessors panic on a mismatched kind before a pointer is read. `out`
    // is a valid out-pointer.
    unsafe {
        match kind {
            AstType::Id => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_id),
                    out,
                    args.location(0),
                    args.string(1),
                )
            }
            AstType::Variable => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_variable),
                    out,
                    args.location(0),
                    args.string(1),
                )
            }
            AstType::SymbolicTerm => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_symbolic_term),
                    out,
                    args.location(0),
                    args.symbol(1),
                )
            }
            AstType::UnaryOperation => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_unary_operation),
                    out,
                    args.location(0),
                    args.number(1),
                    args.ast(2),
                )
            }
            AstType::BinaryOperation => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_binary_operation),
                    out,
                    args.location(0),
                    args.number(1),
                    args.ast(2),
                    args.ast(3),
                )
            }
            AstType::Interval => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_interval),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast(2),
                )
            }
            AstType::Function => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_function),
                    out,
                    args.location(0),
                    args.string(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                    args.number(3),
                )
            }
            AstType::Pool => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_pool),
                    out,
                    args.location(0),
                    args.ast_array(1),
                    args.ast_array_len(1),
                )
            }
            AstType::BooleanConstant => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_boolean_constant),
                    out,
                    args.number(0),
                )
            }
            AstType::SymbolicAtom => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_symbolic_atom),
                    out,
                    args.ast(0),
                )
            }
            AstType::Comparison => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_comparison),
                    out,
                    args.ast(0),
                    args.ast_array(1),
                    args.ast_array_len(1),
                )
            }
            AstType::Guard => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_guard),
                    out,
                    args.number(0),
                    args.ast(1),
                )
            }
            AstType::ConditionalLiteral => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_conditional_literal),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::Aggregate => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_aggregate),
                    out,
                    args.location(0),
                    args.optional_ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                    args.optional_ast(3),
                )
            }
            AstType::BodyAggregateElement => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_body_aggregate_element),
                    out,
                    args.ast_array(0),
                    args.ast_array_len(0),
                    args.ast_array(1),
                    args.ast_array_len(1),
                )
            }
            AstType::BodyAggregate => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_body_aggregate),
                    out,
                    args.location(0),
                    args.optional_ast(1),
                    args.number(2),
                    args.ast_array(3),
                    args.ast_array_len(3),
                    args.optional_ast(4),
                )
            }
            AstType::HeadAggregateElement => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_head_aggregate_element),
                    out,
                    args.ast_array(0),
                    args.ast_array_len(0),
                    args.ast(1),
                )
            }
            AstType::HeadAggregate => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_head_aggregate),
                    out,
                    args.location(0),
                    args.optional_ast(1),
                    args.number(2),
                    args.ast_array(3),
                    args.ast_array_len(3),
                    args.optional_ast(4),
                )
            }
            AstType::Disjunction => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_disjunction),
                    out,
                    args.location(0),
                    args.ast_array(1),
                    args.ast_array_len(1),
                )
            }
            AstType::TheorySequence => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_sequence),
                    out,
                    args.location(0),
                    args.number(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::TheoryFunction => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_function),
                    out,
                    args.location(0),
                    args.string(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::TheoryUnparsedTermElement => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_unparsed_term_element),
                    out,
                    args.string_array(0),
                    args.string_array_len(0),
                    args.ast(1),
                )
            }
            AstType::TheoryUnparsedTerm => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_unparsed_term),
                    out,
                    args.location(0),
                    args.ast_array(1),
                    args.ast_array_len(1),
                )
            }
            AstType::TheoryGuard => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_guard),
                    out,
                    args.string(0),
                    args.ast(1),
                )
            }
            AstType::TheoryAtomElement => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_atom_element),
                    out,
                    args.ast_array(0),
                    args.ast_array_len(0),
                    args.ast_array(1),
                    args.ast_array_len(1),
                )
            }
            AstType::TheoryAtom => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_atom),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                    args.optional_ast(3),
                )
            }
            AstType::Literal => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_literal),
                    out,
                    args.location(0),
                    args.number(1),
                    args.ast(2),
                )
            }
            AstType::TheoryOperatorDefinition => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_operator_definition),
                    out,
                    args.location(0),
                    args.string(1),
                    args.number(2),
                    args.number(3),
                )
            }
            AstType::TheoryTermDefinition => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_term_definition),
                    out,
                    args.location(0),
                    args.string(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::TheoryGuardDefinition => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_guard_definition),
                    out,
                    args.string_array(0),
                    args.string_array_len(0),
                    args.string(1),
                )
            }
            AstType::TheoryAtomDefinition => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_atom_definition),
                    out,
                    args.location(0),
                    args.number(1),
                    args.string(2),
                    args.number(3),
                    args.string(4),
                    args.optional_ast(5),
                )
            }
            AstType::Rule => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_rule),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::Definition => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_definition),
                    out,
                    args.location(0),
                    args.string(1),
                    args.ast(2),
                    args.number(3),
                )
            }
            AstType::ShowSignature => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_show_signature),
                    out,
                    args.location(0),
                    args.string(1),
                    args.number(2),
                    args.number(3),
                )
            }
            AstType::ShowTerm => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_show_term),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::Minimize => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_minimize),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast(2),
                    args.ast_array(3),
                    args.ast_array_len(3),
                    args.ast_array(4),
                    args.ast_array_len(4),
                )
            }
            AstType::Script => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_script),
                    out,
                    args.location(0),
                    args.string(1),
                    args.string(2),
                )
            }
            AstType::Program => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_program),
                    out,
                    args.location(0),
                    args.string(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::External => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_external),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                    args.ast(3),
                )
            }
            AstType::Edge => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_edge),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast(2),
                    args.ast_array(3),
                    args.ast_array_len(3),
                )
            }
            AstType::Heuristic => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_heuristic),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                    args.ast(3),
                    args.ast(4),
                    args.ast(5),
                )
            }
            AstType::ProjectAtom => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_project_atom),
                    out,
                    args.location(0),
                    args.ast(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                )
            }
            AstType::ProjectSignature => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_project_signature),
                    out,
                    args.location(0),
                    args.string(1),
                    args.number(2),
                    args.number(3),
                )
            }
            AstType::Defined => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_defined),
                    out,
                    args.location(0),
                    args.string(1),
                    args.number(2),
                    args.number(3),
                )
            }
            AstType::TheoryDefinition => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_theory_definition),
                    out,
                    args.location(0),
                    args.string(1),
                    args.ast_array(2),
                    args.ast_array_len(2),
                    args.ast_array(3),
                    args.ast_array_len(3),
                )
            }
            AstType::Comment => {
                ffi::clingo_ast_build(
                    c_int_of(ffi::clingo_ast_type_comment),
                    out,
                    args.location(0),
                    args.string(1),
                    args.number(2),
                )
            }
            AstType::Other(_) => {
                unreachable!("`ast_build` rejects an unknown node type first")
            }
        }
    }
}
