//! What the code generated by `clingox-derive` calls (DESIGN S18). It is
//! public so that the generated code can reach it, and not part of the stable
//! API.

use crate::convert::{self, ToSymbol};
use crate::error::{Error, ErrorKind, Result};
use crate::symbol::{Sign, Symbol};

/// The positive function `name(arguments)`.
pub fn function(name: &str, arguments: &[Symbol]) -> Result<Symbol> {
    Symbol::function(name, arguments)
}

/// The negative function `-name(arguments)`.
pub fn negative_function(name: &str, arguments: &[Symbol]) -> Result<Symbol> {
    Symbol::function_with_sign(name, arguments, Sign::Negative)
}

/// The tuple of `elements`.
pub fn tuple(elements: &[Symbol]) -> Result<Symbol> {
    Symbol::tuple(elements)
}

/// The number `n`.
#[must_use]
pub fn number(n: i32) -> Symbol {
    Symbol::number(n)
}

/// The string symbol with content `s`.
pub fn string(s: &str) -> Result<Symbol> {
    Symbol::string(s)
}

/// `#sup`.
#[must_use]
pub fn supremum() -> Symbol {
    Symbol::supremum()
}

/// `#inf`.
#[must_use]
pub fn infimum() -> Symbol {
    Symbol::infimum()
}

/// Converts a spliced or field value.
pub fn to_symbol<T: ToSymbol + ?Sized>(value: &T) -> Result<Symbol> {
    value.to_symbol()
}

/// Runs the closure that builds a `sym!` symbol, so that its `?` stays inside
/// the macro.
pub fn build(f: impl FnOnce() -> Result<Symbol>) -> Result<Symbol> {
    f()
}

/// A `#[clingo(string)]` field as a symbol.
pub fn string_field(value: &str) -> Result<Symbol> {
    Symbol::string(value)
}

/// A `#[clingo(constant)]` field as a symbol.
pub fn constant_field(value: &str) -> Result<Symbol> {
    if value.is_empty() {
        // `Symbol::function("", &[])` is the empty tuple, not a constant.
        return Err(Error::new(
            ErrorKind::Conversion,
            "an empty `String` has no clingo constant; it would be the empty tuple",
        ));
    }
    Symbol::function(value, &[])
}

/// A `#[clingo(string)]` field read from a symbol: a string symbol only.
pub fn string_from(symbol: Symbol) -> Result<String> {
    symbol
        .as_string()
        .map(str::to_owned)
        .ok_or_else(|| convert::mismatch(symbol, "a string"))
}

/// A `#[clingo(constant)]` field read from a symbol: a positive function
/// without arguments and with a non-empty name.
pub fn constant_from(symbol: Symbol) -> Result<String> {
    parts(symbol)
        .filter(|(_, arguments)| arguments.is_empty())
        .map(|(name, _)| name.to_owned())
        .ok_or_else(|| convert::mismatch(symbol, "a constant"))
}

/// The name and arguments of a positive function with a non-empty name; a
/// derived type matches on these.
pub fn parts(symbol: Symbol) -> Option<(&'static str, &'static [Symbol])> {
    let (name, arguments, sign) = symbol.function_parts()?;
    (sign == Sign::Positive && !name.is_empty()).then_some((name, arguments))
}

/// The error for a symbol that is not the derived struct `rust_name`.
pub fn mismatch(symbol: Symbol, rust_name: &str, name: &str, arity: usize) -> Error {
    convert::mismatch(
        symbol,
        &format!("a `{rust_name}`, which is `{name}/{arity}`"),
    )
}

/// The error for a symbol that matches no variant of the derived enum
/// `rust_name`.
pub fn no_variant(symbol: Symbol, rust_name: &str) -> Error {
    Error::new(
        ErrorKind::Conversion,
        format!("`{symbol}` matches no variant of `{rust_name}`"),
    )
}

/// Names the field whose conversion failed, and the symbol it came from.
pub fn field<T>(result: Result<T>, symbol: Symbol, rust_name: &str, field: &str) -> Result<T> {
    result.map_err(|err| {
        err.with_kind(ErrorKind::Conversion).context(format!(
            "reading `{symbol}` as `{rust_name}`, field `{field}`"
        ))
    })
}
