// @generated by cargo xtask ast-codegen; do not edit.
//! The typed layer over `clingo_ast_build`: the enum types of the number
//! attributes, one constructor per node type, the visitor, and two
//! crate-private tables the setters and the visitor read.
//!
//! Generated from clingo's own constructor table by `cargo xtask ast-codegen`.
#![allow(
    clippy::match_same_arms,
    clippy::too_many_lines,
    reason = "generated from a table: arms repeat, and the functions are as long as the table"
)]
use super::{Ast, AstType, Attribute, AttributeType, Span};
use crate::Symbol;
use crate::error::{Error, ErrorKind, Result};
use crate::raw::{self, BuildArg};
/// The sign of a literal: none, `not` or `not not`.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `LiteralSign::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=2`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum LiteralSign {
    /// `clingo_ast_sign_no_sign`, 0.
    NoSign = 0,
    /// `clingo_ast_sign_negation`, 1.
    Negation = 1,
    /// `clingo_ast_sign_double_negation`, 2.
    DoubleNegation = 2,
}
impl From<LiteralSign> for i32 {
    fn from(value: LiteralSign) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for LiteralSign {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(LiteralSign::NoSign),
            1 => Ok(LiteralSign::Negation),
            2 => Ok(LiteralSign::DoubleNegation),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `LiteralSign` (0..=2)"),
                    ),
                )
            }
        }
    }
}
/// A comparison operator, as used by a guard.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `ComparisonOperator::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=5`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum ComparisonOperator {
    /// `clingo_ast_comparison_operator_greater_than`, 0.
    GreaterThan = 0,
    /// `clingo_ast_comparison_operator_less_than`, 1.
    LessThan = 1,
    /// `clingo_ast_comparison_operator_less_equal`, 2.
    LessEqual = 2,
    /// `clingo_ast_comparison_operator_greater_equal`, 3.
    GreaterEqual = 3,
    /// `clingo_ast_comparison_operator_not_equal`, 4.
    NotEqual = 4,
    /// `clingo_ast_comparison_operator_equal`, 5.
    Equal = 5,
}
impl From<ComparisonOperator> for i32 {
    fn from(value: ComparisonOperator) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for ComparisonOperator {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(ComparisonOperator::GreaterThan),
            1 => Ok(ComparisonOperator::LessThan),
            2 => Ok(ComparisonOperator::LessEqual),
            3 => Ok(ComparisonOperator::GreaterEqual),
            4 => Ok(ComparisonOperator::NotEqual),
            5 => Ok(ComparisonOperator::Equal),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `ComparisonOperator` (0..=5)"),
                    ),
                )
            }
        }
    }
}
/// A unary operator of a term.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `UnaryOperator::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=2`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum UnaryOperator {
    /// `clingo_ast_unary_operator_minus`, 0.
    Minus = 0,
    /// `clingo_ast_unary_operator_negation`, 1.
    Negation = 1,
    /// `clingo_ast_unary_operator_absolute`, 2.
    Absolute = 2,
}
impl From<UnaryOperator> for i32 {
    fn from(value: UnaryOperator) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for UnaryOperator {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(UnaryOperator::Minus),
            1 => Ok(UnaryOperator::Negation),
            2 => Ok(UnaryOperator::Absolute),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `UnaryOperator` (0..=2)"),
                    ),
                )
            }
        }
    }
}
/// A binary operator of a term.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `BinaryOperator::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=8`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum BinaryOperator {
    /// `clingo_ast_binary_operator_xor`, 0.
    Xor = 0,
    /// `clingo_ast_binary_operator_or`, 1.
    Or = 1,
    /// `clingo_ast_binary_operator_and`, 2.
    And = 2,
    /// `clingo_ast_binary_operator_plus`, 3.
    Plus = 3,
    /// `clingo_ast_binary_operator_minus`, 4.
    Minus = 4,
    /// `clingo_ast_binary_operator_multiplication`, 5.
    Multiplication = 5,
    /// `clingo_ast_binary_operator_division`, 6.
    Division = 6,
    /// `clingo_ast_binary_operator_modulo`, 7.
    Modulo = 7,
    /// `clingo_ast_binary_operator_power`, 8.
    Power = 8,
}
impl From<BinaryOperator> for i32 {
    fn from(value: BinaryOperator) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for BinaryOperator {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(BinaryOperator::Xor),
            1 => Ok(BinaryOperator::Or),
            2 => Ok(BinaryOperator::And),
            3 => Ok(BinaryOperator::Plus),
            4 => Ok(BinaryOperator::Minus),
            5 => Ok(BinaryOperator::Multiplication),
            6 => Ok(BinaryOperator::Division),
            7 => Ok(BinaryOperator::Modulo),
            8 => Ok(BinaryOperator::Power),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `BinaryOperator` (0..=8)"),
                    ),
                )
            }
        }
    }
}
/// The function of an aggregate.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `AggregateFunction::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=4`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum AggregateFunction {
    /// `clingo_ast_aggregate_function_count`, 0.
    Count = 0,
    /// `clingo_ast_aggregate_function_sum`, 1.
    Sum = 1,
    /// `clingo_ast_aggregate_function_sump`, 2.
    SumPlus = 2,
    /// `clingo_ast_aggregate_function_min`, 3.
    Min = 3,
    /// `clingo_ast_aggregate_function_max`, 4.
    Max = 4,
}
impl From<AggregateFunction> for i32 {
    fn from(value: AggregateFunction) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for AggregateFunction {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(AggregateFunction::Count),
            1 => Ok(AggregateFunction::Sum),
            2 => Ok(AggregateFunction::SumPlus),
            3 => Ok(AggregateFunction::Min),
            4 => Ok(AggregateFunction::Max),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `AggregateFunction` (0..=4)"),
                    ),
                )
            }
        }
    }
}
/// The kind of bracket around a theory sequence.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `TheorySequenceType::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=2`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TheorySequenceType {
    /// `clingo_ast_theory_sequence_type_tuple`, 0.
    Tuple = 0,
    /// `clingo_ast_theory_sequence_type_set`, 1.
    Set = 1,
    /// `clingo_ast_theory_sequence_type_list`, 2.
    List = 2,
}
impl From<TheorySequenceType> for i32 {
    fn from(value: TheorySequenceType) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for TheorySequenceType {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(TheorySequenceType::Tuple),
            1 => Ok(TheorySequenceType::Set),
            2 => Ok(TheorySequenceType::List),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `TheorySequenceType` (0..=2)"),
                    ),
                )
            }
        }
    }
}
/// The arity and associativity of a theory operator.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `TheoryOperatorType::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=2`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TheoryOperatorType {
    /// `clingo_ast_theory_operator_type_unary`, 0.
    Unary = 0,
    /// `clingo_ast_theory_operator_type_binary_left`, 1.
    BinaryLeft = 1,
    /// `clingo_ast_theory_operator_type_binary_right`, 2.
    BinaryRight = 2,
}
impl From<TheoryOperatorType> for i32 {
    fn from(value: TheoryOperatorType) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for TheoryOperatorType {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(TheoryOperatorType::Unary),
            1 => Ok(TheoryOperatorType::BinaryLeft),
            2 => Ok(TheoryOperatorType::BinaryRight),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `TheoryOperatorType` (0..=2)"),
                    ),
                )
            }
        }
    }
}
/// Where a theory atom may occur.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `TheoryAtomType::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=3`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TheoryAtomType {
    /// `clingo_ast_theory_atom_definition_type_head`, 0.
    Head = 0,
    /// `clingo_ast_theory_atom_definition_type_body`, 1.
    Body = 1,
    /// `clingo_ast_theory_atom_definition_type_any`, 2.
    Any = 2,
    /// `clingo_ast_theory_atom_definition_type_directive`, 3.
    Directive = 3,
}
impl From<TheoryAtomType> for i32 {
    fn from(value: TheoryAtomType) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for TheoryAtomType {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(TheoryAtomType::Head),
            1 => Ok(TheoryAtomType::Body),
            2 => Ok(TheoryAtomType::Any),
            3 => Ok(TheoryAtomType::Directive),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `TheoryAtomType` (0..=3)"),
                    ),
                )
            }
        }
    }
}
/// The kind of a comment.
///
/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and
/// `CommentType::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..=1`.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum CommentType {
    /// `clingo_comment_type_line`, 0.
    Line = 0,
    /// `clingo_comment_type_block`, 1.
    Block = 1,
}
impl From<CommentType> for i32 {
    fn from(value: CommentType) -> i32 {
        value as i32
    }
}
impl TryFrom<i32> for CommentType {
    type Error = Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(CommentType::Line),
            1 => Ok(CommentType::Block),
            _ => {
                Err(
                    Error::new(
                        ErrorKind::InvalidInput,
                        format!("{value} is not a `CommentType` (0..=1)"),
                    ),
                )
            }
        }
    }
}
/// Builds a [`AstType::Id`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn id(location: &Span, name: &str) -> Result<Ast> {
    raw::ast_build(AstType::Id, &[BuildArg::Span(location), BuildArg::Str(name)])
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `id` node"))
}
/// Builds a [`AstType::Variable`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn variable(location: &Span, name: &str) -> Result<Ast> {
    raw::ast_build(AstType::Variable, &[BuildArg::Span(location), BuildArg::Str(name)])
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `variable` node"))
}
/// Builds a [`AstType::SymbolicTerm`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `symbol`: [`Attribute::Symbol`], a `Symbol`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn symbolic_term(location: &Span, symbol: Symbol) -> Result<Ast> {
    raw::ast_build(
            AstType::SymbolicTerm,
            &[BuildArg::Span(location), BuildArg::Symbol(symbol)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `symbolic_term` node"))
}
/// Builds a [`AstType::UnaryOperation`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `operator_type`: [`Attribute::OperatorType`], a `UnaryOperator`.
/// - `argument`: [`Attribute::Argument`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn unary_operation(
    location: &Span,
    operator_type: UnaryOperator,
    argument: &Ast,
) -> Result<Ast> {
    raw::ast_build(
            AstType::UnaryOperation,
            &[
                BuildArg::Span(location),
                BuildArg::Number(i32::from(operator_type)),
                BuildArg::Ast(argument),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `unary_operation` node"))
}
/// Builds a [`AstType::BinaryOperation`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `operator_type`: [`Attribute::OperatorType`], a `BinaryOperator`.
/// - `left`: [`Attribute::Left`], a `&Ast`.
/// - `right`: [`Attribute::Right`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn binary_operation(
    location: &Span,
    operator_type: BinaryOperator,
    left: &Ast,
    right: &Ast,
) -> Result<Ast> {
    raw::ast_build(
            AstType::BinaryOperation,
            &[
                BuildArg::Span(location),
                BuildArg::Number(i32::from(operator_type)),
                BuildArg::Ast(left),
                BuildArg::Ast(right),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `binary_operation` node"))
}
/// Builds a [`AstType::Interval`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `left`: [`Attribute::Left`], a `&Ast`.
/// - `right`: [`Attribute::Right`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn interval(location: &Span, left: &Ast, right: &Ast) -> Result<Ast> {
    raw::ast_build(
            AstType::Interval,
            &[BuildArg::Span(location), BuildArg::Ast(left), BuildArg::Ast(right)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `interval` node"))
}
/// Builds a [`AstType::Function`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `arguments`: [`Attribute::Arguments`], a `&[Ast]`.
/// - `external`: [`Attribute::External`], a `bool`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// # Examples
///
/// ```
/// use clingox::ast::{self, Span};
///
/// let span = Span::new("<example>", 1, 1, "<example>", 1, 5)?;
/// let x = ast::variable(&span, "X")?;
/// let call = ast::function(&span, "f", &[x.clone()], false)?;
/// assert_eq!(call.to_string(), "f(X)");
/// // The argument is borrowed, not consumed:
/// assert_eq!(x.to_string(), "X");
/// # Ok::<(), clingox::Error>(())
/// ```
pub fn function(
    location: &Span,
    name: &str,
    arguments: &[Ast],
    external: bool,
) -> Result<Ast> {
    raw::ast_build(
            AstType::Function,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::AstArray(arguments),
                BuildArg::Number(i32::from(external)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `function` node"))
}
/// Builds a [`AstType::Pool`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `arguments`: [`Attribute::Arguments`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn pool(location: &Span, arguments: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::Pool,
            &[BuildArg::Span(location), BuildArg::AstArray(arguments)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `pool` node"))
}
/// Builds a [`AstType::BooleanConstant`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `value`: [`Attribute::Value`], a `bool`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn boolean_constant(value: bool) -> Result<Ast> {
    raw::ast_build(AstType::BooleanConstant, &[BuildArg::Number(i32::from(value))])
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `boolean_constant` node"))
}
/// Builds a [`AstType::SymbolicAtom`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `symbol`: [`Attribute::Symbol`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn symbolic_atom(symbol: &Ast) -> Result<Ast> {
    raw::ast_build(AstType::SymbolicAtom, &[BuildArg::Ast(symbol)])
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `symbolic_atom` node"))
}
/// Builds a [`AstType::Comparison`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `term`: [`Attribute::Term`], a `&Ast`.
/// - `guards`: [`Attribute::Guards`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn comparison(term: &Ast, guards: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::Comparison,
            &[BuildArg::Ast(term), BuildArg::AstArray(guards)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `comparison` node"))
}
/// Builds a [`AstType::Guard`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `comparison`: [`Attribute::Comparison`], a `ComparisonOperator`.
/// - `term`: [`Attribute::Term`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn guard(comparison: ComparisonOperator, term: &Ast) -> Result<Ast> {
    raw::ast_build(
            AstType::Guard,
            &[BuildArg::Number(i32::from(comparison)), BuildArg::Ast(term)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `guard` node"))
}
/// Builds a [`AstType::ConditionalLiteral`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `literal`: [`Attribute::Literal`], a `&Ast`.
/// - `condition`: [`Attribute::Condition`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn conditional_literal(
    location: &Span,
    literal: &Ast,
    condition: &[Ast],
) -> Result<Ast> {
    raw::ast_build(
            AstType::ConditionalLiteral,
            &[
                BuildArg::Span(location),
                BuildArg::Ast(literal),
                BuildArg::AstArray(condition),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `conditional_literal` node"))
}
/// Builds a [`AstType::Aggregate`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `left_guard`: [`Attribute::LeftGuard`], a `Option<&Ast>`.
/// - `elements`: [`Attribute::Elements`], a `&[Ast]`.
/// - `right_guard`: [`Attribute::RightGuard`], a `Option<&Ast>`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn aggregate(
    location: &Span,
    left_guard: Option<&Ast>,
    elements: &[Ast],
    right_guard: Option<&Ast>,
) -> Result<Ast> {
    raw::ast_build(
            AstType::Aggregate,
            &[
                BuildArg::Span(location),
                BuildArg::OptionalAst(left_guard),
                BuildArg::AstArray(elements),
                BuildArg::OptionalAst(right_guard),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `aggregate` node"))
}
/// Builds a [`AstType::BodyAggregateElement`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `terms`: [`Attribute::Terms`], a `&[Ast]`.
/// - `condition`: [`Attribute::Condition`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn body_aggregate_element(terms: &[Ast], condition: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::BodyAggregateElement,
            &[BuildArg::AstArray(terms), BuildArg::AstArray(condition)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `body_aggregate_element` node"))
}
/// Builds a [`AstType::BodyAggregate`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `left_guard`: [`Attribute::LeftGuard`], a `Option<&Ast>`.
/// - `function`: [`Attribute::Function`], a `AggregateFunction`.
/// - `elements`: [`Attribute::Elements`], a `&[Ast]`.
/// - `right_guard`: [`Attribute::RightGuard`], a `Option<&Ast>`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn body_aggregate(
    location: &Span,
    left_guard: Option<&Ast>,
    function: AggregateFunction,
    elements: &[Ast],
    right_guard: Option<&Ast>,
) -> Result<Ast> {
    raw::ast_build(
            AstType::BodyAggregate,
            &[
                BuildArg::Span(location),
                BuildArg::OptionalAst(left_guard),
                BuildArg::Number(i32::from(function)),
                BuildArg::AstArray(elements),
                BuildArg::OptionalAst(right_guard),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `body_aggregate` node"))
}
/// Builds a [`AstType::HeadAggregateElement`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `terms`: [`Attribute::Terms`], a `&[Ast]`.
/// - `condition`: [`Attribute::Condition`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn head_aggregate_element(terms: &[Ast], condition: &Ast) -> Result<Ast> {
    raw::ast_build(
            AstType::HeadAggregateElement,
            &[BuildArg::AstArray(terms), BuildArg::Ast(condition)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `head_aggregate_element` node"))
}
/// Builds a [`AstType::HeadAggregate`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `left_guard`: [`Attribute::LeftGuard`], a `Option<&Ast>`.
/// - `function`: [`Attribute::Function`], a `AggregateFunction`.
/// - `elements`: [`Attribute::Elements`], a `&[Ast]`.
/// - `right_guard`: [`Attribute::RightGuard`], a `Option<&Ast>`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn head_aggregate(
    location: &Span,
    left_guard: Option<&Ast>,
    function: AggregateFunction,
    elements: &[Ast],
    right_guard: Option<&Ast>,
) -> Result<Ast> {
    raw::ast_build(
            AstType::HeadAggregate,
            &[
                BuildArg::Span(location),
                BuildArg::OptionalAst(left_guard),
                BuildArg::Number(i32::from(function)),
                BuildArg::AstArray(elements),
                BuildArg::OptionalAst(right_guard),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `head_aggregate` node"))
}
/// Builds a [`AstType::Disjunction`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `elements`: [`Attribute::Elements`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn disjunction(location: &Span, elements: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::Disjunction,
            &[BuildArg::Span(location), BuildArg::AstArray(elements)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `disjunction` node"))
}
/// Builds a [`AstType::TheorySequence`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `sequence_type`: [`Attribute::SequenceType`], a `TheorySequenceType`.
/// - `terms`: [`Attribute::Terms`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_sequence(
    location: &Span,
    sequence_type: TheorySequenceType,
    terms: &[Ast],
) -> Result<Ast> {
    raw::ast_build(
            AstType::TheorySequence,
            &[
                BuildArg::Span(location),
                BuildArg::Number(i32::from(sequence_type)),
                BuildArg::AstArray(terms),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_sequence` node"))
}
/// Builds a [`AstType::TheoryFunction`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `arguments`: [`Attribute::Arguments`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_function(location: &Span, name: &str, arguments: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryFunction,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::AstArray(arguments),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_function` node"))
}
/// Builds a [`AstType::TheoryUnparsedTermElement`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `operators`: [`Attribute::Operators`], a `&[impl AsRef<str>]`.
/// - `term`: [`Attribute::Term`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_unparsed_term_element(
    operators: &[impl AsRef<str>],
    term: &Ast,
) -> Result<Ast> {
    let operators: Vec<&str> = operators.iter().map(AsRef::as_ref).collect();
    raw::ast_build(
            AstType::TheoryUnparsedTermElement,
            &[BuildArg::StrArray(&operators), BuildArg::Ast(term)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_unparsed_term_element` node"))
}
/// Builds a [`AstType::TheoryUnparsedTerm`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `elements`: [`Attribute::Elements`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_unparsed_term(location: &Span, elements: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryUnparsedTerm,
            &[BuildArg::Span(location), BuildArg::AstArray(elements)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_unparsed_term` node"))
}
/// Builds a [`AstType::TheoryGuard`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `operator_name`: [`Attribute::OperatorName`], a `&str`.
/// - `term`: [`Attribute::Term`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_guard(operator_name: &str, term: &Ast) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryGuard,
            &[BuildArg::Str(operator_name), BuildArg::Ast(term)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_guard` node"))
}
/// Builds a [`AstType::TheoryAtomElement`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `terms`: [`Attribute::Terms`], a `&[Ast]`.
/// - `condition`: [`Attribute::Condition`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_atom_element(terms: &[Ast], condition: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryAtomElement,
            &[BuildArg::AstArray(terms), BuildArg::AstArray(condition)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_atom_element` node"))
}
/// Builds a [`AstType::TheoryAtom`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `term`: [`Attribute::Term`], a `&Ast`.
/// - `elements`: [`Attribute::Elements`], a `&[Ast]`.
/// - `guard`: [`Attribute::Guard`], a `Option<&Ast>`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_atom(
    location: &Span,
    term: &Ast,
    elements: &[Ast],
    guard: Option<&Ast>,
) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryAtom,
            &[
                BuildArg::Span(location),
                BuildArg::Ast(term),
                BuildArg::AstArray(elements),
                BuildArg::OptionalAst(guard),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_atom` node"))
}
/// Builds a [`AstType::Literal`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `sign`: [`Attribute::Sign`], a `LiteralSign`.
/// - `atom`: [`Attribute::Atom`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn literal(location: &Span, sign: LiteralSign, atom: &Ast) -> Result<Ast> {
    raw::ast_build(
            AstType::Literal,
            &[
                BuildArg::Span(location),
                BuildArg::Number(i32::from(sign)),
                BuildArg::Ast(atom),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `literal` node"))
}
/// Builds a [`AstType::TheoryOperatorDefinition`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `priority`: [`Attribute::Priority`], a `i32`.
/// - `operator_type`: [`Attribute::OperatorType`], a `TheoryOperatorType`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_operator_definition(
    location: &Span,
    name: &str,
    priority: i32,
    operator_type: TheoryOperatorType,
) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryOperatorDefinition,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::Number(priority),
                BuildArg::Number(i32::from(operator_type)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_operator_definition` node"))
}
/// Builds a [`AstType::TheoryTermDefinition`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `operators`: [`Attribute::Operators`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_term_definition(
    location: &Span,
    name: &str,
    operators: &[Ast],
) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryTermDefinition,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::AstArray(operators),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_term_definition` node"))
}
/// Builds a [`AstType::TheoryGuardDefinition`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `operators`: [`Attribute::Operators`], a `&[impl AsRef<str>]`.
/// - `term`: [`Attribute::Term`], a `&str`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_guard_definition(
    operators: &[impl AsRef<str>],
    term: &str,
) -> Result<Ast> {
    let operators: Vec<&str> = operators.iter().map(AsRef::as_ref).collect();
    raw::ast_build(
            AstType::TheoryGuardDefinition,
            &[BuildArg::StrArray(&operators), BuildArg::Str(term)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_guard_definition` node"))
}
/// Builds a [`AstType::TheoryAtomDefinition`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `atom_type`: [`Attribute::AtomType`], a `TheoryAtomType`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `arity`: [`Attribute::Arity`], a `i32`.
/// - `term`: [`Attribute::Term`], a `&str`.
/// - `guard`: [`Attribute::Guard`], a `Option<&Ast>`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::InvalidInput`] if `arity` is negative;
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// A huge arity is accepted, because it is clingo's own limit: adding a
/// `project_signature` with an arity in the hundreds of millions to a program
/// makes clingo allocate one variable per argument until memory runs out
/// (UPSTREAM-ISSUES U48), as the text `#project p/4294967295.` does.
pub fn theory_atom_definition(
    location: &Span,
    atom_type: TheoryAtomType,
    name: &str,
    arity: i32,
    term: &str,
    guard: Option<&Ast>,
) -> Result<Ast> {
    if arity < 0 {
        return Err(
            Error::new(
                ErrorKind::InvalidInput,
                format!("{arity} is not an arity, which is at least 0"),
            ),
        );
    }
    raw::ast_build(
            AstType::TheoryAtomDefinition,
            &[
                BuildArg::Span(location),
                BuildArg::Number(i32::from(atom_type)),
                BuildArg::Str(name),
                BuildArg::Number(arity),
                BuildArg::Str(term),
                BuildArg::OptionalAst(guard),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_atom_definition` node"))
}
/// Builds a [`AstType::Rule`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `head`: [`Attribute::Head`], a `&Ast`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// # Examples
///
/// A fact, `a.`, built from a symbolic term:
///
/// ```
/// use clingox::Symbol;
/// use clingox::ast::{self, LiteralSign, Span};
///
/// let span = Span::new("<example>", 1, 1, "<example>", 1, 3)?;
/// let term = ast::symbolic_term(&span, Symbol::function("a", &[])?)?;
/// let atom = ast::symbolic_atom(&term)?;
/// let head = ast::literal(&span, LiteralSign::NoSign, &atom)?;
/// let rule = ast::rule(&span, &head, &[])?;
/// assert_eq!(rule.to_string(), "a.");
/// # Ok::<(), clingox::Error>(())
/// ```
pub fn rule(location: &Span, head: &Ast, body: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::Rule,
            &[BuildArg::Span(location), BuildArg::Ast(head), BuildArg::AstArray(body)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `rule` node"))
}
/// Builds a [`AstType::Definition`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `value`: [`Attribute::Value`], a `&Ast`.
/// - `is_default`: [`Attribute::IsDefault`], a `bool`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn definition(
    location: &Span,
    name: &str,
    value: &Ast,
    is_default: bool,
) -> Result<Ast> {
    raw::ast_build(
            AstType::Definition,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::Ast(value),
                BuildArg::Number(i32::from(is_default)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `definition` node"))
}
/// Builds a [`AstType::ShowSignature`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `arity`: [`Attribute::Arity`], a `i32`.
/// - `positive`: [`Attribute::Positive`], a `bool`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::InvalidInput`] if `arity` is negative;
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// A huge arity is accepted, because it is clingo's own limit: adding a
/// `project_signature` with an arity in the hundreds of millions to a program
/// makes clingo allocate one variable per argument until memory runs out
/// (UPSTREAM-ISSUES U48), as the text `#project p/4294967295.` does.
pub fn show_signature(
    location: &Span,
    name: &str,
    arity: i32,
    positive: bool,
) -> Result<Ast> {
    if arity < 0 {
        return Err(
            Error::new(
                ErrorKind::InvalidInput,
                format!("{arity} is not an arity, which is at least 0"),
            ),
        );
    }
    raw::ast_build(
            AstType::ShowSignature,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::Number(arity),
                BuildArg::Number(i32::from(positive)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `show_signature` node"))
}
/// Builds a [`AstType::ShowTerm`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `term`: [`Attribute::Term`], a `&Ast`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn show_term(location: &Span, term: &Ast, body: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::ShowTerm,
            &[BuildArg::Span(location), BuildArg::Ast(term), BuildArg::AstArray(body)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `show_term` node"))
}
/// Builds a [`AstType::Minimize`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `weight`: [`Attribute::Weight`], a `&Ast`.
/// - `priority`: [`Attribute::Priority`], a `&Ast`.
/// - `terms`: [`Attribute::Terms`], a `&[Ast]`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn minimize(
    location: &Span,
    weight: &Ast,
    priority: &Ast,
    terms: &[Ast],
    body: &[Ast],
) -> Result<Ast> {
    raw::ast_build(
            AstType::Minimize,
            &[
                BuildArg::Span(location),
                BuildArg::Ast(weight),
                BuildArg::Ast(priority),
                BuildArg::AstArray(terms),
                BuildArg::AstArray(body),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `minimize` node"))
}
/// Builds a [`AstType::Script`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `code`: [`Attribute::Code`], a `&str`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn script(location: &Span, name: &str, code: &str) -> Result<Ast> {
    raw::ast_build(
            AstType::Script,
            &[BuildArg::Span(location), BuildArg::Str(name), BuildArg::Str(code)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `script` node"))
}
/// Builds a [`AstType::Program`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `parameters`: [`Attribute::Parameters`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn program(location: &Span, name: &str, parameters: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::Program,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::AstArray(parameters),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `program` node"))
}
/// Builds a [`AstType::External`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `atom`: [`Attribute::Atom`], a `&Ast`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
/// - `external_type`: [`Attribute::ExternalType`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// # The type argument
///
/// `external_type` is a term node, not an enum constant: clingo 5.8 reads the
/// truth value the atom starts with from a term, one of the constants `true`,
/// `false`, `free` and `release` (clingo 5.6 took a number). Build it with
/// [`symbolic_term`] from `Symbol::function("true", &[])`. Any other term is
/// accepted here and silently ignored when the program is grounded.
///
/// # Examples
///
/// ```
/// use clingox::Symbol;
/// use clingox::ast::{self, Span};
///
/// let span = Span::new("<example>", 1, 1, "<example>", 1, 15)?;
/// let atom = ast::symbolic_atom(&ast::symbolic_term(&span, Symbol::function("e", &[])?)?)?;
/// let kind = ast::symbolic_term(&span, Symbol::function("true", &[])?)?;
/// let external = ast::external(&span, &atom, &[], &kind)?;
/// assert_eq!(external.to_string(), "#external e. [true]");
/// # Ok::<(), clingox::Error>(())
/// ```
pub fn external(
    location: &Span,
    atom: &Ast,
    body: &[Ast],
    external_type: &Ast,
) -> Result<Ast> {
    raw::ast_build(
            AstType::External,
            &[
                BuildArg::Span(location),
                BuildArg::Ast(atom),
                BuildArg::AstArray(body),
                BuildArg::Ast(external_type),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `external` node"))
}
/// Builds a [`AstType::Edge`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `node_u`: [`Attribute::NodeU`], a `&Ast`.
/// - `node_v`: [`Attribute::NodeV`], a `&Ast`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn edge(location: &Span, node_u: &Ast, node_v: &Ast, body: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::Edge,
            &[
                BuildArg::Span(location),
                BuildArg::Ast(node_u),
                BuildArg::Ast(node_v),
                BuildArg::AstArray(body),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `edge` node"))
}
/// Builds a [`AstType::Heuristic`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `atom`: [`Attribute::Atom`], a `&Ast`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
/// - `bias`: [`Attribute::Bias`], a `&Ast`.
/// - `priority`: [`Attribute::Priority`], a `&Ast`.
/// - `modifier`: [`Attribute::Modifier`], a `&Ast`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn heuristic(
    location: &Span,
    atom: &Ast,
    body: &[Ast],
    bias: &Ast,
    priority: &Ast,
    modifier: &Ast,
) -> Result<Ast> {
    raw::ast_build(
            AstType::Heuristic,
            &[
                BuildArg::Span(location),
                BuildArg::Ast(atom),
                BuildArg::AstArray(body),
                BuildArg::Ast(bias),
                BuildArg::Ast(priority),
                BuildArg::Ast(modifier),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `heuristic` node"))
}
/// Builds a [`AstType::ProjectAtom`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `atom`: [`Attribute::Atom`], a `&Ast`.
/// - `body`: [`Attribute::Body`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn project_atom(location: &Span, atom: &Ast, body: &[Ast]) -> Result<Ast> {
    raw::ast_build(
            AstType::ProjectAtom,
            &[BuildArg::Span(location), BuildArg::Ast(atom), BuildArg::AstArray(body)],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `project_atom` node"))
}
/// Builds a [`AstType::ProjectSignature`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `arity`: [`Attribute::Arity`], a `i32`.
/// - `positive`: [`Attribute::Positive`], a `bool`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::InvalidInput`] if `arity` is negative;
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// A huge arity is accepted, because it is clingo's own limit: adding a
/// `project_signature` with an arity in the hundreds of millions to a program
/// makes clingo allocate one variable per argument until memory runs out
/// (UPSTREAM-ISSUES U48), as the text `#project p/4294967295.` does.
pub fn project_signature(
    location: &Span,
    name: &str,
    arity: i32,
    positive: bool,
) -> Result<Ast> {
    if arity < 0 {
        return Err(
            Error::new(
                ErrorKind::InvalidInput,
                format!("{arity} is not an arity, which is at least 0"),
            ),
        );
    }
    raw::ast_build(
            AstType::ProjectSignature,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::Number(arity),
                BuildArg::Number(i32::from(positive)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `project_signature` node"))
}
/// Builds a [`AstType::Defined`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `arity`: [`Attribute::Arity`], a `i32`.
/// - `positive`: [`Attribute::Positive`], a `bool`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::InvalidInput`] if `arity` is negative;
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
///
/// A huge arity is accepted, because it is clingo's own limit: adding a
/// `project_signature` with an arity in the hundreds of millions to a program
/// makes clingo allocate one variable per argument until memory runs out
/// (UPSTREAM-ISSUES U48), as the text `#project p/4294967295.` does.
pub fn defined(location: &Span, name: &str, arity: i32, positive: bool) -> Result<Ast> {
    if arity < 0 {
        return Err(
            Error::new(
                ErrorKind::InvalidInput,
                format!("{arity} is not an arity, which is at least 0"),
            ),
        );
    }
    raw::ast_build(
            AstType::Defined,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::Number(arity),
                BuildArg::Number(i32::from(positive)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `defined` node"))
}
/// Builds a [`AstType::TheoryDefinition`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `name`: [`Attribute::Name`], a `&str`.
/// - `terms`: [`Attribute::Terms`], a `&[Ast]`.
/// - `atoms`: [`Attribute::Atoms`], a `&[Ast]`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn theory_definition(
    location: &Span,
    name: &str,
    terms: &[Ast],
    atoms: &[Ast],
) -> Result<Ast> {
    raw::ast_build(
            AstType::TheoryDefinition,
            &[
                BuildArg::Span(location),
                BuildArg::Str(name),
                BuildArg::AstArray(terms),
                BuildArg::AstArray(atoms),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `theory_definition` node"))
}
/// Builds a [`AstType::Comment`] node.
///
/// The arguments follow clingo's constructor table for the type, in order:
///
/// - `location`: [`Attribute::Location`], a `&Span`.
/// - `value`: [`Attribute::Value`], a `&str`.
/// - `comment_type`: [`Attribute::CommentType`], a `CommentType`.
///
/// Every node argument is borrowed: the new node holds its own reference, and
/// the caller's handles stay valid. The result is a new top node, and shares
/// its children with the arguments. What kind of node an argument is is not
/// checked.
///
/// # Errors
///
/// - [`ErrorKind::Nul`] if a string contains a NUL byte;
/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory.
pub fn comment(location: &Span, value: &str, comment_type: CommentType) -> Result<Ast> {
    raw::ast_build(
            AstType::Comment,
            &[
                BuildArg::Span(location),
                BuildArg::Str(value),
                BuildArg::Number(i32::from(comment_type)),
            ],
        )
        .map(Ast::from_raw)
        .map_err(|e| e.context("building a `comment` node"))
}
/// The values a `number` attribute may take on a node of a given type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum NumberDomain {
    /// Any `i32`.
    Any,
    /// A boolean, stored as 0 or 1.
    Bool,
    /// `0..=max`: an enum's constants, or `0..=i32::MAX` for an arity.
    Range(i32),
}
/// The domain of `attribute` on a node of type `kind` (`set_number`).
pub(crate) fn number_domain(kind: AstType, attribute: Attribute) -> NumberDomain {
    match (kind, attribute) {
        (AstType::UnaryOperation, Attribute::OperatorType) => NumberDomain::Range(2),
        (AstType::BinaryOperation, Attribute::OperatorType) => NumberDomain::Range(8),
        (AstType::Function, Attribute::External) => NumberDomain::Bool,
        (AstType::BooleanConstant, Attribute::Value) => NumberDomain::Bool,
        (AstType::Guard, Attribute::Comparison) => NumberDomain::Range(5),
        (AstType::BodyAggregate, Attribute::Function) => NumberDomain::Range(4),
        (AstType::HeadAggregate, Attribute::Function) => NumberDomain::Range(4),
        (AstType::TheorySequence, Attribute::SequenceType) => NumberDomain::Range(2),
        (AstType::Literal, Attribute::Sign) => NumberDomain::Range(2),
        (AstType::TheoryOperatorDefinition, Attribute::OperatorType) => {
            NumberDomain::Range(2)
        }
        (AstType::TheoryAtomDefinition, Attribute::AtomType) => NumberDomain::Range(3),
        (AstType::TheoryAtomDefinition, Attribute::Arity) => {
            NumberDomain::Range(i32::MAX)
        }
        (AstType::Definition, Attribute::IsDefault) => NumberDomain::Bool,
        (AstType::ShowSignature, Attribute::Arity) => NumberDomain::Range(i32::MAX),
        (AstType::ShowSignature, Attribute::Positive) => NumberDomain::Bool,
        (AstType::ProjectSignature, Attribute::Arity) => NumberDomain::Range(i32::MAX),
        (AstType::ProjectSignature, Attribute::Positive) => NumberDomain::Bool,
        (AstType::Defined, Attribute::Arity) => NumberDomain::Range(i32::MAX),
        (AstType::Defined, Attribute::Positive) => NumberDomain::Bool,
        (AstType::Comment, Attribute::CommentType) => NumberDomain::Range(1),
        _ => NumberDomain::Any,
    }
}
/// The attributes of `kind` that hold nodes, in constructor order.
pub(crate) fn child_attributes(kind: AstType) -> &'static [(Attribute, AttributeType)] {
    match kind {
        AstType::UnaryOperation => &[(Attribute::Argument, AttributeType::Ast)],
        AstType::BinaryOperation => {
            &[
                (Attribute::Left, AttributeType::Ast),
                (Attribute::Right, AttributeType::Ast),
            ]
        }
        AstType::Interval => {
            &[
                (Attribute::Left, AttributeType::Ast),
                (Attribute::Right, AttributeType::Ast),
            ]
        }
        AstType::Function => &[(Attribute::Arguments, AttributeType::AstArray)],
        AstType::Pool => &[(Attribute::Arguments, AttributeType::AstArray)],
        AstType::SymbolicAtom => &[(Attribute::Symbol, AttributeType::Ast)],
        AstType::Comparison => {
            &[
                (Attribute::Term, AttributeType::Ast),
                (Attribute::Guards, AttributeType::AstArray),
            ]
        }
        AstType::Guard => &[(Attribute::Term, AttributeType::Ast)],
        AstType::ConditionalLiteral => {
            &[
                (Attribute::Literal, AttributeType::Ast),
                (Attribute::Condition, AttributeType::AstArray),
            ]
        }
        AstType::Aggregate => {
            &[
                (Attribute::LeftGuard, AttributeType::OptionalAst),
                (Attribute::Elements, AttributeType::AstArray),
                (Attribute::RightGuard, AttributeType::OptionalAst),
            ]
        }
        AstType::BodyAggregateElement => {
            &[
                (Attribute::Terms, AttributeType::AstArray),
                (Attribute::Condition, AttributeType::AstArray),
            ]
        }
        AstType::BodyAggregate => {
            &[
                (Attribute::LeftGuard, AttributeType::OptionalAst),
                (Attribute::Elements, AttributeType::AstArray),
                (Attribute::RightGuard, AttributeType::OptionalAst),
            ]
        }
        AstType::HeadAggregateElement => {
            &[
                (Attribute::Terms, AttributeType::AstArray),
                (Attribute::Condition, AttributeType::Ast),
            ]
        }
        AstType::HeadAggregate => {
            &[
                (Attribute::LeftGuard, AttributeType::OptionalAst),
                (Attribute::Elements, AttributeType::AstArray),
                (Attribute::RightGuard, AttributeType::OptionalAst),
            ]
        }
        AstType::Disjunction => &[(Attribute::Elements, AttributeType::AstArray)],
        AstType::TheorySequence => &[(Attribute::Terms, AttributeType::AstArray)],
        AstType::TheoryFunction => &[(Attribute::Arguments, AttributeType::AstArray)],
        AstType::TheoryUnparsedTermElement => &[(Attribute::Term, AttributeType::Ast)],
        AstType::TheoryUnparsedTerm => &[(Attribute::Elements, AttributeType::AstArray)],
        AstType::TheoryGuard => &[(Attribute::Term, AttributeType::Ast)],
        AstType::TheoryAtomElement => {
            &[
                (Attribute::Terms, AttributeType::AstArray),
                (Attribute::Condition, AttributeType::AstArray),
            ]
        }
        AstType::TheoryAtom => {
            &[
                (Attribute::Term, AttributeType::Ast),
                (Attribute::Elements, AttributeType::AstArray),
                (Attribute::Guard, AttributeType::OptionalAst),
            ]
        }
        AstType::Literal => &[(Attribute::Atom, AttributeType::Ast)],
        AstType::TheoryTermDefinition => {
            &[(Attribute::Operators, AttributeType::AstArray)]
        }
        AstType::TheoryAtomDefinition => {
            &[(Attribute::Guard, AttributeType::OptionalAst)]
        }
        AstType::Rule => {
            &[
                (Attribute::Head, AttributeType::Ast),
                (Attribute::Body, AttributeType::AstArray),
            ]
        }
        AstType::Definition => &[(Attribute::Value, AttributeType::Ast)],
        AstType::ShowTerm => {
            &[
                (Attribute::Term, AttributeType::Ast),
                (Attribute::Body, AttributeType::AstArray),
            ]
        }
        AstType::Minimize => {
            &[
                (Attribute::Weight, AttributeType::Ast),
                (Attribute::Priority, AttributeType::Ast),
                (Attribute::Terms, AttributeType::AstArray),
                (Attribute::Body, AttributeType::AstArray),
            ]
        }
        AstType::Program => &[(Attribute::Parameters, AttributeType::AstArray)],
        AstType::External => {
            &[
                (Attribute::Atom, AttributeType::Ast),
                (Attribute::Body, AttributeType::AstArray),
                (Attribute::ExternalType, AttributeType::Ast),
            ]
        }
        AstType::Edge => {
            &[
                (Attribute::NodeU, AttributeType::Ast),
                (Attribute::NodeV, AttributeType::Ast),
                (Attribute::Body, AttributeType::AstArray),
            ]
        }
        AstType::Heuristic => {
            &[
                (Attribute::Atom, AttributeType::Ast),
                (Attribute::Body, AttributeType::AstArray),
                (Attribute::Bias, AttributeType::Ast),
                (Attribute::Priority, AttributeType::Ast),
                (Attribute::Modifier, AttributeType::Ast),
            ]
        }
        AstType::ProjectAtom => {
            &[
                (Attribute::Atom, AttributeType::Ast),
                (Attribute::Body, AttributeType::AstArray),
            ]
        }
        AstType::TheoryDefinition => {
            &[
                (Attribute::Terms, AttributeType::AstArray),
                (Attribute::Atoms, AttributeType::AstArray),
            ]
        }
        _ => &[],
    }
}
/// Rewrites a syntax tree: one method per node type, each defaulting to
/// [`walk`], which visits the node's children.
///
/// Every method takes a borrowed node and returns an owned one. Returning
/// a clone of the argument means "unchanged"; returning any other node
/// replaces it, and the replacement may be of a different type. A child
/// counts as changed exactly when the node returned for it is not
/// [`Ast::ptr_eq`] to the original (identity, as pyclingo's `is not`), so
/// an unchanged subtree is shared, not copied, and [`walk`] returns the
/// very node it was given when nothing below it changed.
///
/// The first error any method returns stops the whole walk and is returned
/// unchanged. The original tree is never modified by `walk`, also on an
/// error.
///
/// A visitor must not edit the tree it walks, whether through a setter on
/// the node it was given or on one of its children: [`walk`] reads the
/// children as it goes, so the result of such an edit is a silently
/// partial rewrite. Nothing is unsafe about it (every index is checked),
/// but it is not the tree you meant. Edit a `copy()` instead.
///
/// `visit` dispatches on the node's type and should not be overridden.
/// The trait is object safe: `&mut dyn Visitor` works.
///
/// # Deleting and inserting array elements
///
/// [`walk`] replaces array elements one for one, as pyclingo's
/// `Transformer` does by default. To delete or insert elements, call
/// [`walk`] and edit the result, but `copy()` it first when it is
/// [`Ast::ptr_eq`] to the input: nothing below it changed, so it *is* the
/// original node, and editing it would edit the original tree.
///
/// ```
/// use clingox::ast::{self, Ast, AstType, Attribute, Visitor, walk};
/// use clingox::Result;
///
/// /// Drops the first body literal of every rule.
/// struct DropFirst;
///
/// impl Visitor for DropFirst {
///     fn visit_rule(&mut self, node: &Ast) -> Result<Ast> {
///         let walked = walk(self, node)?;
///         let edited = if walked.ptr_eq(node) { walked.copy()? } else { walked };
///         if edited.ast_array_len(Attribute::Body)? > 0 {
///             edited.delete_ast_at(Attribute::Body, 0)?;
///         }
///         Ok(edited)
///     }
/// }
///
/// let mut rules = Vec::new();
/// ast::parse_string("h :- a, b.", |node| {
///     if node.ast_type() == AstType::Rule {
///         rules.push(node);
///     }
///     Ok(())
/// })?;
/// let rewritten = DropFirst.visit(&rules[0])?;
/// assert_eq!(rewritten.to_string(), "h :- b.");
/// assert_eq!(rules[0].to_string(), "h :- a; b.");
/// # Ok::<(), clingox::Error>(())
/// ```
pub trait Visitor {
    /// Dispatches on `node.ast_type()` to the matching `visit_*` method.
    ///
    /// # Errors
    ///
    /// Whatever the method it calls returns.
    fn visit(&mut self, node: &Ast) -> Result<Ast> {
        match node.ast_type() {
            AstType::Id => self.visit_id(node),
            AstType::Variable => self.visit_variable(node),
            AstType::SymbolicTerm => self.visit_symbolic_term(node),
            AstType::UnaryOperation => self.visit_unary_operation(node),
            AstType::BinaryOperation => self.visit_binary_operation(node),
            AstType::Interval => self.visit_interval(node),
            AstType::Function => self.visit_function(node),
            AstType::Pool => self.visit_pool(node),
            AstType::BooleanConstant => self.visit_boolean_constant(node),
            AstType::SymbolicAtom => self.visit_symbolic_atom(node),
            AstType::Comparison => self.visit_comparison(node),
            AstType::Guard => self.visit_guard(node),
            AstType::ConditionalLiteral => self.visit_conditional_literal(node),
            AstType::Aggregate => self.visit_aggregate(node),
            AstType::BodyAggregateElement => self.visit_body_aggregate_element(node),
            AstType::BodyAggregate => self.visit_body_aggregate(node),
            AstType::HeadAggregateElement => self.visit_head_aggregate_element(node),
            AstType::HeadAggregate => self.visit_head_aggregate(node),
            AstType::Disjunction => self.visit_disjunction(node),
            AstType::TheorySequence => self.visit_theory_sequence(node),
            AstType::TheoryFunction => self.visit_theory_function(node),
            AstType::TheoryUnparsedTermElement => {
                self.visit_theory_unparsed_term_element(node)
            }
            AstType::TheoryUnparsedTerm => self.visit_theory_unparsed_term(node),
            AstType::TheoryGuard => self.visit_theory_guard(node),
            AstType::TheoryAtomElement => self.visit_theory_atom_element(node),
            AstType::TheoryAtom => self.visit_theory_atom(node),
            AstType::Literal => self.visit_literal(node),
            AstType::TheoryOperatorDefinition => {
                self.visit_theory_operator_definition(node)
            }
            AstType::TheoryTermDefinition => self.visit_theory_term_definition(node),
            AstType::TheoryGuardDefinition => self.visit_theory_guard_definition(node),
            AstType::TheoryAtomDefinition => self.visit_theory_atom_definition(node),
            AstType::Rule => self.visit_rule(node),
            AstType::Definition => self.visit_definition(node),
            AstType::ShowSignature => self.visit_show_signature(node),
            AstType::ShowTerm => self.visit_show_term(node),
            AstType::Minimize => self.visit_minimize(node),
            AstType::Script => self.visit_script(node),
            AstType::Program => self.visit_program(node),
            AstType::External => self.visit_external(node),
            AstType::Edge => self.visit_edge(node),
            AstType::Heuristic => self.visit_heuristic(node),
            AstType::ProjectAtom => self.visit_project_atom(node),
            AstType::ProjectSignature => self.visit_project_signature(node),
            AstType::Defined => self.visit_defined(node),
            AstType::TheoryDefinition => self.visit_theory_definition(node),
            AstType::Comment => self.visit_comment(node),
            AstType::Other(_) => self.visit_other(node),
        }
    }
    /// Visits a [`AstType::Id`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_id(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Variable`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_variable(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::SymbolicTerm`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_symbolic_term(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::UnaryOperation`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_unary_operation(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::BinaryOperation`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_binary_operation(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Interval`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_interval(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Function`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_function(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Pool`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_pool(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::BooleanConstant`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_boolean_constant(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::SymbolicAtom`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_symbolic_atom(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Comparison`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_comparison(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Guard`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_guard(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::ConditionalLiteral`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_conditional_literal(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Aggregate`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_aggregate(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::BodyAggregateElement`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_body_aggregate_element(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::BodyAggregate`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_body_aggregate(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::HeadAggregateElement`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_head_aggregate_element(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::HeadAggregate`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_head_aggregate(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Disjunction`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_disjunction(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheorySequence`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_sequence(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryFunction`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_function(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryUnparsedTermElement`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_unparsed_term_element(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryUnparsedTerm`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_unparsed_term(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryGuard`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_guard(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryAtomElement`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_atom_element(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryAtom`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_atom(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Literal`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_literal(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryOperatorDefinition`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_operator_definition(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryTermDefinition`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_term_definition(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryGuardDefinition`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_guard_definition(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryAtomDefinition`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_atom_definition(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Rule`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_rule(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Definition`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_definition(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::ShowSignature`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_show_signature(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::ShowTerm`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_show_term(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Minimize`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_minimize(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Script`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_script(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Program`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_program(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::External`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_external(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Edge`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_edge(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Heuristic`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_heuristic(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::ProjectAtom`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_project_atom(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::ProjectSignature`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_project_signature(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Defined`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_defined(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::TheoryDefinition`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_theory_definition(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a [`AstType::Comment`] node. Defaults to [`walk`].
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_comment(&mut self, node: &Ast) -> Result<Ast> {
        walk(self, node)
    }
    /// Visits a node of a type this build does not know ([`AstType::Other`]).
    /// Defaults to returning the node unchanged.
    ///
    /// # Errors
    ///
    /// As [`Visitor::visit`].
    fn visit_other(&mut self, node: &Ast) -> Result<Ast> {
        Ok(node.clone())
    }
}
/// Visits the children of `node` through `visitor` and rebuilds `node` when
/// any of them changed.
///
/// For each child attribute of the node's type, in constructor order:
/// an `ast` attribute is visited, an `optional_ast` is skipped when it is
/// `None` and visited otherwise, and every element of an `ast_array` is
/// visited in index order, one replacement per element (the length cannot
/// change here). Other attributes (`location`, names, symbols, numbers,
/// strings) are never visited.
///
/// If no child changed, the result is a clone of `node`, so it is
/// [`Ast::ptr_eq`] to it and nothing is allocated. Otherwise the result is
/// `node.copy()` with only the changed children replaced: unchanged
/// children and siblings stay shared with the original, and every other
/// attribute, the location included, is kept. The original is never
/// modified.
///
/// An override can call `walk` before or after its own edits. See
/// [`Visitor`] for how to delete or insert array elements.
///
/// # Stack use
///
/// `walk` recurses once per level of the tree, through
/// [`Visitor::visit`], like pyclingo's `Transformer`, and has no depth
/// limit of its own. A tree deep enough to exhaust the thread's stack
/// overflows it. Printing, comparing and dropping such a tree recurse in
/// clingo the same way, so a tree that clingo itself can print on a
/// thread can also be walked on it; run a visitor over very deep trees on
/// a thread with a large stack.
///
/// # Errors
///
/// The first error any `visit_*` method, setter or `copy` reports, which
/// is returned unchanged.
pub fn walk<V: Visitor + ?Sized>(visitor: &mut V, node: &Ast) -> Result<Ast> {
    let mut rebuilt: Option<Ast> = None;
    for &(attribute, kind) in child_attributes(node.ast_type()) {
        match kind {
            AttributeType::Ast => {
                let child = node.ast(attribute)?;
                let visited = visitor.visit(&child)?;
                if !visited.ptr_eq(&child) {
                    copy_of(&mut rebuilt, node)?.set_ast_fresh(attribute, &visited)?;
                }
            }
            AttributeType::OptionalAst => {
                if let Some(child) = node.optional_ast(attribute)? {
                    let visited = visitor.visit(&child)?;
                    if !visited.ptr_eq(&child) {
                        copy_of(&mut rebuilt, node)?
                            .set_optional_ast_fresh(attribute, &visited)?;
                    }
                }
            }
            AttributeType::AstArray => {
                for index in 0..node.ast_array_len(attribute)? {
                    let child = node.ast_at(attribute, index)?;
                    let visited = visitor.visit(&child)?;
                    if !visited.ptr_eq(&child) {
                        copy_of(&mut rebuilt, node)?
                            .set_ast_at_fresh(attribute, index, &visited)?;
                    }
                }
            }
            _ => {}
        }
    }
    Ok(rebuilt.unwrap_or_else(|| node.clone()))
}
/// The private copy `walk` edits: made on the first change, and a handle to
/// the same node afterwards.
///
/// This is why `walk` may use the setters that skip the cycle check: the copy
/// is new, and only `walk` holds a handle to it until `walk` returns. A
/// replacement a visitor returns was made before the copy could be reached,
/// so it cannot reach the copy, and adding it below the copy cannot close a
/// cycle. The original tree is only read.
fn copy_of(rebuilt: &mut Option<Ast>, node: &Ast) -> Result<Ast> {
    if let Some(copy) = rebuilt {
        return Ok(copy.clone());
    }
    let copy = node.copy()?;
    *rebuilt = Some(copy.clone());
    Ok(copy)
}
