//! Raw FFI bindings to the [clingo](https://potassco.org/clingo/) 5.8 C API, and
//! the build of clingo itself.
//!
//! This is the low-level crate behind [clingox](https://docs.rs/clingox), which
//! is the safe API. Every item here mirrors a declaration in `clingo.h` under
//! its C name, and none of it is safe to call without reading the header's
//! contract.
//!
//! # Building clingo
//!
//! By default clingo 5.8.2 is built from the vendored source (feature
//! `vendored`), with the patches listed in [`PATCHES`] applied to a copy of it.
//! The build needs `CMake` and a C++ compiler, and no network. A system library
//! can be used instead through `CLINGO_LIB_DIR`, `CLINGO_INCLUDE_DIR`,
//! `CLINGO_STATIC`, `CLINGO_THREADS` and `CLINGOX_SYS_NO_VENDOR`; it must be at
//! least 5.8.1 and older than 5.9.0, and it gets no patch. The
//! [installation chapter](https://papilionem.github.io/clingox/getting-started/installation.html)
//! of the clingox guide describes each variable.
//!
//! | Feature | Default | What it does |
//! |---|---|---|
//! | `vendored` | yes | Builds clingo from the source in this crate. |
//! | `threads` | yes | Builds clasp with threads; see [`HAS_THREADS`]. |
//!
//! This crate declares `links = "clingo"`, so it cannot share a dependency graph
//! with Potassco's `clingo-sys`: both would define the same C symbols.

#![deny(unsafe_op_in_unsafe_fn)]
#![deny(clippy::undocumented_unsafe_blocks)]
#![deny(clippy::missing_safety_doc)]

// The bindings are generated by `cargo xtask bindgen` and keep clingo's C names,
// so the naming lints do not apply. Their doc comments are clingo's Doxygen text,
// which rustdoc and clippy would read as broken links, HTML and Markdown lists,
// and items the header leaves undocumented have no doc comment to generate.
#[allow(non_camel_case_types, non_upper_case_globals, non_snake_case, missing_docs)]
#[allow(rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags, rustdoc::bare_urls)]
#[allow(clippy::doc_lazy_continuation, clippy::doc_markdown)]
#[rustfmt::skip]
mod bindings;

pub use bindings::*;

/// The clingo version of the header these bindings were generated from, as
/// `(major, minor, revision)`.
///
/// It is built from the header's `CLINGO_VERSION_*` macros. Compare it with
/// [`clingo_version`] to check the library that was actually linked.
pub const CLINGO_VERSION: (u32, u32, u32) = (
    CLINGO_VERSION_MAJOR,
    CLINGO_VERSION_MINOR,
    CLINGO_VERSION_REVISION,
);

// `build.rs` sets `clingox_sys_build` whenever it runs. systest's ABI
// generator expands this file on its own, outside that build: there the file
// below does not exist, and these Rust-only constants have no C counterpart
// to check, so they are left out.

/// The build facts `build.rs` writes: whether clingo was vendored, whether
/// clasp has threads, and the patches applied.
#[cfg(clingox_sys_build)]
mod build_config {
    include!(concat!(env!("OUT_DIR"), "/build_config.rs"));
}

/// Whether the linked clasp was built with threads, which asynchronous
/// solving, timeouts and more than one solver thread need.
///
/// For the vendored build it is what the build script configured: the
/// feature `threads`, on a target that can run threads (every target except
/// WebAssembly without the `atomics` target feature). For a system library it
/// is the value of `CLINGO_THREADS` at build time: `1`, or unset, for a clingo
/// built with threads (the default of clingo's `CMake` build), `0` for one
/// built without.
#[cfg(clingox_sys_build)]
pub const HAS_THREADS: bool = build_config::HAS_THREADS;

/// Whether clingo was built from the vendored source, rather than taken from a
/// system installation.
#[cfg(clingox_sys_build)]
pub const VENDORED: bool = build_config::VENDORED;

/// The entries of clingox's `docs/dev/UPSTREAM-ISSUES.md` whose fixes are
/// patched into this build, in the order the patches were applied, which is
/// file-name order: `["U1", "U19", "U2", "U35", "U46", "U47", "U49", "U50"]` for the
/// vendored build, none for a system library.
#[cfg(clingox_sys_build)]
pub const PATCHES: &[&str] = build_config::PATCHES;
