//! `cargo xtask ast-codegen`: the typed layer over `clingo_ast_build`, written
//! from clingo's own constructor table.
//!
//! The tables `g_clingo_ast_constructors` and `g_clingo_ast_attribute_names`
//! are read at run time through `clingox-sys`, because clingo exports them for
//! exactly this purpose ("enough information to auto-generate code for
//! language bindings", `clingo.h`). The committed `bindings.rs` is read only as
//! text, to enumerate the `clingo_ast_*` constants the tables must agree with.
//!
//! Two files come out: `clingox/src/ast/generated.rs`, the safe layer (the
//! nine enum types, the constructors, the visitor and two crate-private
//! tables), and `clingox/src/raw/ast_generated.rs`, the one place the variadic
//! `clingo_ast_build` is called. Both go through `syn` and `prettyplease`, so
//! the bytes do not depend on the installed `rustfmt`, and `cargo xtask check`
//! compares them with the committed files.

use std::collections::BTreeMap;
use std::ffi::CStr;
use std::fmt::Write as _;
use std::path::PathBuf;

use clingox_sys as ffi;

use crate::bindings;
use crate::util::{Result, root};

const HEADER: &str = "// @generated by cargo xtask ast-codegen; do not edit.\n";

/// The number of `clingo_ast_attribute_type_*` kinds.
const ATTRIBUTE_TYPES: usize = 8;
const NUMBER: usize = ffi::clingo_ast_attribute_type_number as usize;
const SYMBOL: usize = ffi::clingo_ast_attribute_type_symbol as usize;
const LOCATION: usize = ffi::clingo_ast_attribute_type_location as usize;
const STRING: usize = ffi::clingo_ast_attribute_type_string as usize;
const AST: usize = ffi::clingo_ast_attribute_type_ast as usize;
const OPTIONAL_AST: usize = ffi::clingo_ast_attribute_type_optional_ast as usize;
const STRING_ARRAY: usize = ffi::clingo_ast_attribute_type_string_array as usize;
const AST_ARRAY: usize = ffi::clingo_ast_attribute_type_ast_array as usize;

/// A number attribute whose values are a closed set: the Rust enum that types
/// it, and where it is used.
struct EnumGroup {
    /// The C type of the constants, `clingo_ast_sign_e`.
    c_type: &'static str,
    rust_name: &'static str,
    doc: &'static str,
    /// Constructor and attribute names that take this enum.
    used_by: &'static [(&'static str, &'static str)],
    /// The constants' suffixes whose Rust names differ from their camel case.
    renames: &'static [(&'static str, &'static str)],
}

/// The nine enum types (the table is not in the constructor table, so the
/// generator carries the mapping; assertion 4 guards its completeness).
const GROUPS: [EnumGroup; 9] = [
    EnumGroup {
        c_type: "clingo_ast_sign_e",
        rust_name: "LiteralSign",
        doc: "The sign of a literal: none, `not` or `not not`.",
        used_by: &[("literal", "sign")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_ast_comparison_operator_e",
        rust_name: "ComparisonOperator",
        doc: "A comparison operator, as used by a guard.",
        used_by: &[("guard", "comparison")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_ast_unary_operator_e",
        rust_name: "UnaryOperator",
        doc: "A unary operator of a term.",
        used_by: &[("unary_operation", "operator_type")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_ast_binary_operator_e",
        rust_name: "BinaryOperator",
        doc: "A binary operator of a term.",
        used_by: &[("binary_operation", "operator_type")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_ast_aggregate_function_e",
        rust_name: "AggregateFunction",
        doc: "The function of an aggregate.",
        used_by: &[
            ("body_aggregate", "function"),
            ("head_aggregate", "function"),
        ],
        // The header calls the constant `sump`; pyclingo says `SumPlus`.
        renames: &[("sump", "SumPlus")],
    },
    EnumGroup {
        c_type: "clingo_ast_theory_sequence_type_e",
        rust_name: "TheorySequenceType",
        doc: "The kind of bracket around a theory sequence.",
        used_by: &[("theory_sequence", "sequence_type")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_ast_theory_operator_type_e",
        rust_name: "TheoryOperatorType",
        doc: "The arity and associativity of a theory operator.",
        used_by: &[("theory_operator_definition", "operator_type")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_ast_theory_atom_definition_type_e",
        rust_name: "TheoryAtomType",
        doc: "Where a theory atom may occur.",
        used_by: &[("theory_atom_definition", "atom_type")],
        renames: &[],
    },
    EnumGroup {
        c_type: "clingo_comment_type_e",
        rust_name: "CommentType",
        doc: "The kind of a comment.",
        used_by: &[("comment", "comment_type")],
        renames: &[],
    },
];

/// Number attributes that hold a boolean, stored as 0 or 1.
const BOOLEANS: [(&str, &str); 6] = [
    ("boolean_constant", "value"),
    ("function", "external"),
    ("definition", "is_default"),
    ("show_signature", "positive"),
    ("project_signature", "positive"),
    ("defined", "positive"),
];

/// Number attributes that take any `i32`.
const PLAIN_NUMBERS: [(&str, &str); 1] = [("theory_operator_definition", "priority")];

/// Number attributes that take a non-negative `i32`: clingo reads a negative
/// arity as a huge unsigned one and `project_signature` then builds one
/// variable per argument (UPSTREAM-ISSUES U48).
const ARITIES: [(&str, &str); 4] = [
    ("theory_atom_definition", "arity"),
    ("show_signature", "arity"),
    ("project_signature", "arity"),
    ("defined", "arity"),
];

/// Enums of the header that are deliberately not node attribute values: the
/// bit flags `Ast::unpool` takes.
const UNMAPPED_GROUPS: [&str; 1] = ["clingo_ast_unpool_type_e"];

/// Attributes that are not usable as Rust parameter names.
const KEYWORDS: [&str; 6] = ["type", "match", "loop", "ref", "move", "where"];

struct Argument {
    attribute: usize,
    kind: usize,
}

struct Constructor {
    name: String,
    arguments: Vec<Argument>,
}

struct Tables {
    constructors: Vec<Constructor>,
    attributes: Vec<String>,
}

/// One `pub const clingo_x: clingo_x_e = N;` of the bindings.
struct Constant {
    name: String,
    c_type: String,
    value: i64,
}

/// The two generated files, as text.
pub(crate) struct Generated {
    pub(crate) safe: String,
    pub(crate) raw: String,
}

pub(crate) fn safe_output() -> PathBuf {
    root().join("clingox/src/ast/generated.rs")
}

pub(crate) fn raw_output() -> PathBuf {
    root().join("clingox/src/raw/ast_generated.rs")
}

pub(crate) fn write() -> Result<()> {
    let generated = generate()?;
    if let Some(dir) = safe_output().parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(safe_output(), generated.safe)?;
    std::fs::write(raw_output(), generated.raw)?;
    eprintln!("wrote {}", safe_output().display());
    eprintln!("wrote {}", raw_output().display());
    Ok(())
}

/// Generates both files in memory, so `check` can compare without writing.
pub(crate) fn generate() -> Result<Generated> {
    let tables = read_tables()?;
    let constants = read_constants()?;
    assert_tables(&tables, &constants)?;
    let groups = resolve_groups(&constants)?;
    assert_groups(&tables, &groups)?;
    Ok(Generated {
        safe: finish(&safe_source(&tables, &groups))?,
        raw: finish_raw(&raw_source(&tables))?,
    })
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

fn read_tables() -> Result<Tables> {
    // SAFETY: both are plain C structs that clingo's translation unit
    // initializes before `main` (`control.cc`, `g_clingo_ast_*`), and nothing
    // writes to them; copying the two-word struct reads it once.
    let (constructors, names) = unsafe {
        (
            (&raw const ffi::g_clingo_ast_constructors).read(),
            (&raw const ffi::g_clingo_ast_attribute_names).read(),
        )
    };
    // SAFETY: `names` points to `size` NUL-terminated strings with static
    // storage duration (clingo.h, `clingo_ast_attribute_names_t`).
    let name_list = unsafe { std::slice::from_raw_parts(names.names, names.size) };
    let attributes = name_list
        .iter()
        .map(|&name| {
            // SAFETY: each entry is a NUL-terminated string with static storage.
            unsafe { CStr::from_ptr(name) }.to_str().map(str::to_owned)
        })
        .collect::<std::result::Result<Vec<_>, _>>()?;
    // SAFETY: `constructors` points to `size` entries with static storage.
    let entries =
        unsafe { std::slice::from_raw_parts(constructors.constructors, constructors.size) };
    let mut list = Vec::new();
    for entry in entries {
        // SAFETY: `name` is NUL-terminated with static storage, and
        // `arguments` points to `size` entries with static storage.
        let (name, arguments) = unsafe {
            (
                CStr::from_ptr(entry.name).to_str()?.to_owned(),
                std::slice::from_raw_parts(entry.arguments, entry.size),
            )
        };
        list.push(Constructor {
            name,
            arguments: arguments
                .iter()
                .map(|a| {
                    Ok(Argument {
                        attribute: usize::try_from(a.attribute)?,
                        kind: usize::try_from(a.type_)?,
                    })
                })
                .collect::<Result<_>>()?,
        });
    }
    Ok(Tables {
        constructors: list,
        attributes,
    })
}

/// Every integer constant of the committed bindings that has a `_e` C type.
fn read_constants() -> Result<Vec<Constant>> {
    let text = std::fs::read_to_string(bindings::output())?;
    let file = syn::parse_file(&text)?;
    let mut constants = Vec::new();
    for item in file.items {
        let syn::Item::Const(item) = item else {
            continue;
        };
        let syn::Type::Path(ty) = &*item.ty else {
            continue;
        };
        let Some(c_type) = ty.path.get_ident().map(ToString::to_string) else {
            continue;
        };
        if !c_type.ends_with("_e") {
            continue;
        }
        let syn::Expr::Lit(syn::ExprLit {
            lit: syn::Lit::Int(value),
            ..
        }) = &*item.expr
        else {
            continue;
        };
        constants.push(Constant {
            name: item.ident.to_string(),
            c_type,
            value: value.base10_parse()?,
        });
    }
    Ok(constants)
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

fn assert_tables(tables: &Tables, constants: &[Constant]) -> Result<()> {
    let types: Vec<&Constant> = constants
        .iter()
        .filter(|c| c.c_type == "clingo_ast_type_e")
        .collect();
    if types.len() != tables.constructors.len() {
        return Err(format!(
            "the constructor table has {} entries, but the header defines {} clingo_ast_type_* constants",
            tables.constructors.len(),
            types.len()
        )
        .into());
    }
    for (index, constructor) in tables.constructors.iter().enumerate() {
        let constant = format!("clingo_ast_type_{}", constructor.name);
        let found = types.iter().find(|c| c.name == constant);
        match found {
            Some(c) if usize::try_from(c.value) == Ok(index) => {}
            Some(c) => {
                return Err(format!(
                    "constructor {index} is `{}`, but {constant} has value {}",
                    constructor.name, c.value
                )
                .into());
            }
            None => {
                return Err(format!(
                    "constructor {index} is `{}`, but the header has no {constant}",
                    constructor.name
                )
                .into());
            }
        }
        for name in [&constructor.name] {
            if name.is_empty() || name.starts_with('_') {
                return Err(format!("constructor {index} has the unusable name {name:?}").into());
            }
        }
    }

    let attributes: Vec<&Constant> = constants
        .iter()
        .filter(|c| c.c_type == "clingo_ast_attribute_e")
        .collect();
    if attributes.len() != tables.attributes.len() {
        return Err(format!(
            "the attribute name table has {} entries, but the header defines {} clingo_ast_attribute_* constants",
            tables.attributes.len(),
            attributes.len()
        )
        .into());
    }
    for (index, name) in tables.attributes.iter().enumerate() {
        let constant = format!("clingo_ast_attribute_{name}");
        let ok = attributes
            .iter()
            .any(|c| c.name == constant && usize::try_from(c.value) == Ok(index));
        if !ok {
            return Err(format!(
                "attribute name {index} is `{name}`, but the header has no {constant} = {index}"
            )
            .into());
        }
        if KEYWORDS.contains(&name.as_str()) {
            return Err(format!(
                "attribute `{name}` is a Rust keyword; the generator needs a rename"
            )
            .into());
        }
    }

    for constructor in &tables.constructors {
        for argument in &constructor.arguments {
            if argument.attribute >= tables.attributes.len() {
                return Err(format!(
                    "constructor `{}` names attribute {}, beyond the {} names",
                    constructor.name,
                    argument.attribute,
                    tables.attributes.len()
                )
                .into());
            }
            if argument.kind >= ATTRIBUTE_TYPES {
                return Err(format!(
                    "constructor `{}` has an argument of type {}, beyond the {ATTRIBUTE_TYPES} kinds",
                    constructor.name, argument.kind
                )
                .into());
            }
        }
    }
    Ok(())
}

/// The constants of one enum type, in value order, with their Rust names.
struct Group {
    spec: &'static EnumGroup,
    /// `(rust variant, constant name, value)`.
    variants: Vec<(String, String, i64)>,
}

fn resolve_groups(constants: &[Constant]) -> Result<Vec<Group>> {
    // Assertion 4: every enum group of the header is mapped.
    let mut known: BTreeMap<&str, usize> = BTreeMap::new();
    for constant in constants {
        *known.entry(constant.c_type.as_str()).or_default() += 1;
    }
    let structural = [
        "clingo_ast_type_e",
        "clingo_ast_attribute_e",
        "clingo_ast_attribute_type_e",
    ];
    for c_type in known.keys() {
        let is_ast = c_type.starts_with("clingo_ast_") || *c_type == "clingo_comment_type_e";
        if is_ast
            && !structural.contains(c_type)
            && !UNMAPPED_GROUPS.contains(c_type)
            && !GROUPS.iter().any(|group| group.c_type == *c_type)
        {
            return Err(format!(
                "the header defines the enum {c_type}, which the generator does not map; add it to GROUPS in xtask/src/ast_codegen.rs"
            )
            .into());
        }
    }
    let mut groups = Vec::new();
    for spec in &GROUPS {
        let prefix = spec.c_type.trim_end_matches("_e");
        let mut variants: Vec<(String, String, i64)> = constants
            .iter()
            .filter(|c| c.c_type == spec.c_type)
            .map(|c| {
                let suffix = c
                    .name
                    .strip_prefix(prefix)
                    .and_then(|rest| rest.strip_prefix('_'))
                    .unwrap_or(&c.name);
                let name = spec
                    .renames
                    .iter()
                    .find(|(from, _)| *from == suffix)
                    .map_or_else(|| camel(suffix), |(_, to)| (*to).to_owned());
                (name, c.name.clone(), c.value)
            })
            .collect();
        if variants.is_empty() {
            return Err(format!("the header has no constants of type {}", spec.c_type).into());
        }
        variants.sort_by_key(|v| v.2);
        for (index, variant) in variants.iter().enumerate() {
            if usize::try_from(variant.2) != Ok(index) {
                return Err(format!(
                    "{}: the constants are not 0, 1, 2, ...; {} has value {}",
                    spec.c_type, variant.1, variant.2
                )
                .into());
            }
        }
        groups.push(Group { spec, variants });
    }
    Ok(groups)
}

/// Assertion 3: every mapped (constructor, attribute) pair is a number
/// argument, and every other number argument is accounted for.
fn assert_groups(tables: &Tables, groups: &[Group]) -> Result<()> {
    let pairs = groups
        .iter()
        .flat_map(|g| g.spec.used_by.iter())
        .chain(BOOLEANS.iter())
        .chain(PLAIN_NUMBERS.iter())
        .chain(ARITIES.iter());
    for &(constructor, attribute) in pairs {
        let found = tables
            .constructors
            .iter()
            .find(|c| c.name == constructor)
            .is_some_and(|c| {
                c.arguments
                    .iter()
                    .any(|a| a.kind == NUMBER && tables.attributes[a.attribute] == attribute)
            });
        if !found {
            return Err(format!(
                "the generator maps `{constructor}.{attribute}` as a number, but the constructor table has no such argument"
            )
            .into());
        }
    }
    for constructor in &tables.constructors {
        for argument in constructor.arguments.iter().filter(|a| a.kind == NUMBER) {
            let attribute = &tables.attributes[argument.attribute];
            if number_kind(groups, &constructor.name, attribute).is_none() {
                return Err(format!(
                    "the number argument `{}.{attribute}` is not mapped to an enum, a boolean or a plain number in xtask/src/ast_codegen.rs",
                    constructor.name
                )
                .into());
            }
        }
    }
    Ok(())
}

enum NumberKind<'a> {
    Enum(&'a Group),
    Bool,
    Plain,
    NonNegative,
}

fn number_kind<'a>(
    groups: &'a [Group],
    constructor: &str,
    attribute: &str,
) -> Option<NumberKind<'a>> {
    if let Some(group) = groups
        .iter()
        .find(|g| g.spec.used_by.contains(&(constructor, attribute)))
    {
        return Some(NumberKind::Enum(group));
    }
    if BOOLEANS.contains(&(constructor, attribute)) {
        return Some(NumberKind::Bool);
    }
    if ARITIES.contains(&(constructor, attribute)) {
        return Some(NumberKind::NonNegative);
    }
    PLAIN_NUMBERS
        .contains(&(constructor, attribute))
        .then_some(NumberKind::Plain)
}

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

fn camel(snake: &str) -> String {
    snake
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_uppercase().chain(chars).collect::<String>())
                .unwrap_or_default()
        })
        .collect()
}

// ---------------------------------------------------------------------------
// The safe layer
// ---------------------------------------------------------------------------

/// Example text appended to a few constructors' documentation.
fn extra_docs(name: &str) -> &'static str {
    match name {
        "rule" => {
            "///\n\
             /// # Examples\n\
             ///\n\
             /// A fact, `a.`, built from a symbolic term:\n\
             ///\n\
             /// ```\n\
             /// use clingox::Symbol;\n\
             /// use clingox::ast::{self, LiteralSign, Span};\n\
             ///\n\
             /// let span = Span::new(\"<example>\", 1, 1, \"<example>\", 1, 3)?;\n\
             /// let term = ast::symbolic_term(&span, Symbol::function(\"a\", &[])?)?;\n\
             /// let atom = ast::symbolic_atom(&term)?;\n\
             /// let head = ast::literal(&span, LiteralSign::NoSign, &atom)?;\n\
             /// let rule = ast::rule(&span, &head, &[])?;\n\
             /// assert_eq!(rule.to_string(), \"a.\");\n\
             /// # Ok::<(), clingox::Error>(())\n\
             /// ```\n"
        }
        "function" => {
            "///\n\
             /// # Examples\n\
             ///\n\
             /// ```\n\
             /// use clingox::ast::{self, Span};\n\
             ///\n\
             /// let span = Span::new(\"<example>\", 1, 1, \"<example>\", 1, 5)?;\n\
             /// let x = ast::variable(&span, \"X\")?;\n\
             /// let call = ast::function(&span, \"f\", &[x.clone()], false)?;\n\
             /// assert_eq!(call.to_string(), \"f(X)\");\n\
             /// // The argument is borrowed, not consumed:\n\
             /// assert_eq!(x.to_string(), \"X\");\n\
             /// # Ok::<(), clingox::Error>(())\n\
             /// ```\n"
        }
        "external" => {
            "///\n\
             /// # The type argument\n\
             ///\n\
             /// `external_type` is a term node, not an enum constant: clingo 5.8 reads the\n\
             /// truth value the atom starts with from a term, one of the constants `true`,\n\
             /// `false`, `free` and `release` (clingo 5.6 took a number). Build it with\n\
             /// [`symbolic_term`] from `Symbol::function(\"true\", &[])`. Any other term is\n\
             /// accepted here and silently ignored when the program is grounded.\n\
             ///\n\
             /// # Examples\n\
             ///\n\
             /// ```\n\
             /// use clingox::Symbol;\n\
             /// use clingox::ast::{self, Span};\n\
             ///\n\
             /// let span = Span::new(\"<example>\", 1, 1, \"<example>\", 1, 15)?;\n\
             /// let atom = ast::symbolic_atom(&ast::symbolic_term(&span, Symbol::function(\"e\", &[])?)?)?;\n\
             /// let kind = ast::symbolic_term(&span, Symbol::function(\"true\", &[])?)?;\n\
             /// let external = ast::external(&span, &atom, &[], &kind)?;\n\
             /// assert_eq!(external.to_string(), \"#external e. [true]\");\n\
             /// # Ok::<(), clingox::Error>(())\n\
             /// ```\n"
        }
        _ => "",
    }
}

fn safe_source(tables: &Tables, groups: &[Group]) -> String {
    let mut out = String::new();
    out.push_str(
        "//! The typed layer over `clingo_ast_build`: the enum types of the number\n\
         //! attributes, one constructor per node type, the visitor, and two\n\
         //! crate-private tables the setters and the visitor read.\n\
         //!\n\
         //! Generated from clingo's own constructor table by `cargo xtask ast-codegen`.\n\n\
         #![allow(\n\
         \x20   clippy::match_same_arms,\n\
         \x20   clippy::too_many_lines,\n\
         \x20   reason = \"generated from a table: arms repeat, and the functions are as long as the table\"\n\
         )]\n\n\
         use super::{Ast, AstType, Attribute, AttributeType, Span};\n\
         use crate::Symbol;\n\
         use crate::error::{Error, ErrorKind, Result};\n\
         use crate::raw::{self, BuildArg};\n\n",
    );

    for group in groups {
        enum_source(&mut out, group);
    }

    for constructor in &tables.constructors {
        constructor_source(&mut out, tables, groups, constructor);
    }

    tables_source(&mut out, tables, groups);
    visitor_source(&mut out, tables);
    out
}

fn enum_source(out: &mut String, group: &Group) {
    let name = group.spec.rust_name;
    let last = group.variants.last().map_or(0, |v| v.2);
    let _ = writeln!(out, "/// {}", group.spec.doc);
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// Converts to and from the `i32` clingo stores: `i32::from(value)`, and"
    );
    let _ = writeln!(
        out,
        "/// `{name}::try_from(number)`, which is [`ErrorKind::InvalidInput`] outside `0..={last}`."
    );
    out.push_str(
        "#[non_exhaustive]\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n#[repr(i32)]\n",
    );
    let _ = writeln!(out, "pub enum {name} {{");
    for (variant, constant, value) in &group.variants {
        let _ = writeln!(out, "    /// `{constant}`, {value}.");
        let _ = writeln!(out, "    {variant} = {value},");
    }
    out.push_str("}\n\n");
    let _ = writeln!(
        out,
        "impl From<{name}> for i32 {{\n    fn from(value: {name}) -> i32 {{\n        value as i32\n    }}\n}}\n"
    );
    let _ = writeln!(out, "impl TryFrom<i32> for {name} {{");
    out.push_str("    type Error = Error;\n\n");
    out.push_str("    fn try_from(value: i32) -> Result<Self> {\n        match value {\n");
    for (variant, _, value) in &group.variants {
        let _ = writeln!(out, "            {value} => Ok({name}::{variant}),");
    }
    let _ = writeln!(
        out,
        "            _ => Err(Error::new(\n                ErrorKind::InvalidInput,\n                format!(\"{{value}} is not a `{name}` (0..={last})\"),\n            )),"
    );
    out.push_str("        }\n    }\n}\n\n");
}

/// The Rust parameter type, and the expression that turns it into a
/// `BuildArg`, of one constructor argument.
fn parameter(
    groups: &[Group],
    tables: &Tables,
    constructor: &Constructor,
    argument: &Argument,
) -> (String, String, String) {
    let attribute = tables.attributes[argument.attribute].as_str();
    let (ty, arg) = match argument.kind {
        NUMBER => match number_kind(groups, &constructor.name, attribute) {
            Some(NumberKind::Enum(group)) => (
                group.spec.rust_name.to_owned(),
                format!("BuildArg::Number(i32::from({attribute}))"),
            ),
            Some(NumberKind::Bool) => (
                "bool".to_owned(),
                format!("BuildArg::Number(i32::from({attribute}))"),
            ),
            _ => ("i32".to_owned(), format!("BuildArg::Number({attribute})")),
        },
        SYMBOL => (
            "Symbol".to_owned(),
            format!("BuildArg::Symbol({attribute})"),
        ),
        LOCATION => ("&Span".to_owned(), format!("BuildArg::Span({attribute})")),
        STRING => ("&str".to_owned(), format!("BuildArg::Str({attribute})")),
        AST => ("&Ast".to_owned(), format!("BuildArg::Ast({attribute})")),
        OPTIONAL_AST => (
            "Option<&Ast>".to_owned(),
            format!("BuildArg::OptionalAst({attribute})"),
        ),
        STRING_ARRAY => (
            "&[impl AsRef<str>]".to_owned(),
            format!("BuildArg::StrArray(&{attribute})"),
        ),
        AST_ARRAY => (
            "&[Ast]".to_owned(),
            format!("BuildArg::AstArray({attribute})"),
        ),
        other => unreachable!("assert_tables rejected the attribute type {other}"),
    };
    // A string array needs its `&str` view before the call.
    let prelude = if argument.kind == STRING_ARRAY {
        format!(
            "    let {attribute}: Vec<&str> = {attribute}.iter().map(AsRef::as_ref).collect();\n"
        )
    } else if argument.kind == NUMBER
        && matches!(
            number_kind(groups, &constructor.name, attribute),
            Some(NumberKind::NonNegative)
        )
    {
        format!(
            "    if {attribute} < 0 {{\n        return Err(Error::new(\n            ErrorKind::InvalidInput,\n            format!(\"{{{attribute}}} is not an arity, which is at least 0\"),\n        ));\n    }}\n"
        )
    } else {
        String::new()
    };
    (ty, arg, prelude)
}

fn constructor_source(
    out: &mut String,
    tables: &Tables,
    groups: &[Group],
    constructor: &Constructor,
) {
    let name = &constructor.name;
    let variant = camel(name);
    let mut params = Vec::new();
    let mut args = Vec::new();
    let mut prelude = String::new();
    let mut doc_params = String::new();
    let mut nul = false;
    let mut arity = false;
    for argument in &constructor.arguments {
        let attribute = tables.attributes[argument.attribute].as_str();
        let (ty, arg, pre) = parameter(groups, tables, constructor, argument);
        params.push(format!("{attribute}: {ty}"));
        args.push(arg);
        prelude.push_str(&pre);
        nul |= argument.kind == STRING || argument.kind == STRING_ARRAY;
        arity |= argument.kind == NUMBER
            && matches!(
                number_kind(groups, name, attribute),
                Some(NumberKind::NonNegative)
            );
        let _ = writeln!(
            doc_params,
            "/// - `{attribute}`: [`Attribute::{}`], a `{ty}`.",
            camel(attribute)
        );
    }
    let _ = writeln!(out, "/// Builds a [`AstType::{variant}`] node.");
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// The arguments follow clingo's constructor table for the type, in order:"
    );
    let _ = writeln!(out, "///");
    out.push_str(&doc_params);
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// Every node argument is borrowed: the new node holds its own reference, and\n\
         /// the caller's handles stay valid. The result is a new top node, and shares\n\
         /// its children with the arguments. What kind of node an argument is is not\n\
         /// checked."
    );
    let _ = writeln!(out, "///");
    let _ = writeln!(out, "/// # Errors");
    let _ = writeln!(out, "///");
    if arity {
        let _ = writeln!(
            out,
            "/// - [`ErrorKind::InvalidInput`] if `arity` is negative;"
        );
    }
    if nul {
        let _ = writeln!(
            out,
            "/// - [`ErrorKind::Nul`] if a string contains a NUL byte;"
        );
    }
    let _ = writeln!(
        out,
        "/// - [`ErrorKind::BadAlloc`] if clingo runs out of memory."
    );
    if arity {
        let _ = writeln!(out, "///");
        let _ = writeln!(
            out,
            "/// A huge arity is accepted, because it is clingo's own limit: adding a\n\
             /// `project_signature` with an arity in the hundreds of millions to a program\n\
             /// makes clingo allocate one variable per argument until memory runs out\n\
             /// (UPSTREAM-ISSUES U48), as the text `#project p/4294967295.` does."
        );
    }
    out.push_str(extra_docs(name));
    let _ = writeln!(
        out,
        "pub fn {name}({}) -> Result<Ast> {{",
        params.join(", ")
    );
    out.push_str(&prelude);
    let _ = writeln!(
        out,
        "    raw::ast_build(AstType::{variant}, &[{}])\n        .map(Ast::from_raw)\n        .map_err(|e| e.context(\"building a `{name}` node\"))\n}}\n",
        args.join(", ")
    );
}

fn tables_source(out: &mut String, tables: &Tables, groups: &[Group]) {
    out.push_str(
        "/// The values a `number` attribute may take on a node of a given type.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
         pub(crate) enum NumberDomain {\n\
         \x20   /// Any `i32`.\n\
         \x20   Any,\n\
         \x20   /// A boolean, stored as 0 or 1.\n\
         \x20   Bool,\n\
         \x20   /// `0..=max`: an enum's constants, or `0..=i32::MAX` for an arity.\n\
         \x20   Range(i32),\n\
         }\n\n",
    );

    out.push_str(
        "/// The domain of `attribute` on a node of type `kind` (`set_number`).\n\
         pub(crate) fn number_domain(kind: AstType, attribute: Attribute) -> NumberDomain {\n\
         \x20   match (kind, attribute) {\n",
    );
    for constructor in &tables.constructors {
        for argument in constructor.arguments.iter().filter(|a| a.kind == NUMBER) {
            let attribute = tables.attributes[argument.attribute].as_str();
            let domain = match number_kind(groups, &constructor.name, attribute) {
                Some(NumberKind::Enum(group)) => {
                    let max = group.variants.last().map_or(0, |v| v.2);
                    format!("NumberDomain::Range({max})")
                }
                Some(NumberKind::Bool) => "NumberDomain::Bool".to_owned(),
                Some(NumberKind::NonNegative) => "NumberDomain::Range(i32::MAX)".to_owned(),
                _ => continue,
            };
            let _ = writeln!(
                out,
                "        (AstType::{}, Attribute::{}) => {domain},",
                camel(&constructor.name),
                camel(attribute)
            );
        }
    }
    out.push_str("        _ => NumberDomain::Any,\n    }\n}\n\n");

    out.push_str(
        "/// The attributes of `kind` that hold nodes, in constructor order.\n\
         pub(crate) fn child_attributes(kind: AstType) -> &'static [(Attribute, AttributeType)] {\n\
         \x20   match kind {\n",
    );
    for constructor in &tables.constructors {
        let children: Vec<String> = constructor
            .arguments
            .iter()
            .filter(|a| matches!(a.kind, AST | OPTIONAL_AST | AST_ARRAY))
            .map(|a| {
                let kind = match a.kind {
                    AST => "Ast",
                    OPTIONAL_AST => "OptionalAst",
                    _ => "AstArray",
                };
                format!(
                    "(Attribute::{}, AttributeType::{kind})",
                    camel(&tables.attributes[a.attribute])
                )
            })
            .collect();
        if children.is_empty() {
            continue;
        }
        let _ = writeln!(
            out,
            "        AstType::{} => &[{}],",
            camel(&constructor.name),
            children.join(", ")
        );
    }
    out.push_str("        _ => &[],\n    }\n}\n\n");
}

fn visitor_source(out: &mut String, tables: &Tables) {
    out.push_str(
        "/// Rewrites a syntax tree: one method per node type, each defaulting to\n\
         /// [`walk`], which visits the node's children.\n\
         ///\n\
         /// Every method takes a borrowed node and returns an owned one. Returning\n\
         /// a clone of the argument means \"unchanged\"; returning any other node\n\
         /// replaces it, and the replacement may be of a different type. A child\n\
         /// counts as changed exactly when the node returned for it is not\n\
         /// [`Ast::ptr_eq`] to the original (identity, as pyclingo's `is not`), so\n\
         /// an unchanged subtree is shared, not copied, and [`walk`] returns the\n\
         /// very node it was given when nothing below it changed.\n\
         ///\n\
         /// The first error any method returns stops the whole walk and is returned\n\
         /// unchanged. The original tree is never modified by `walk`, also on an\n\
         /// error.\n\
         ///\n\
         /// A visitor must not edit the tree it walks, whether through a setter on\n\
         /// the node it was given or on one of its children: [`walk`] reads the\n\
         /// children as it goes, so the result of such an edit is a silently\n\
         /// partial rewrite. Nothing is unsafe about it (every index is checked),\n\
         /// but it is not the tree you meant. Edit a `copy()` instead.\n\
         ///\n\
         /// `visit` dispatches on the node's type and should not be overridden.\n\
         /// The trait is object safe: `&mut dyn Visitor` works.\n\
         ///\n\
         /// # Deleting and inserting array elements\n\
         ///\n\
         /// [`walk`] replaces array elements one for one, as pyclingo's\n\
         /// `Transformer` does by default. To delete or insert elements, call\n\
         /// [`walk`] and edit the result, but `copy()` it first when it is\n\
         /// [`Ast::ptr_eq`] to the input: nothing below it changed, so it *is* the\n\
         /// original node, and editing it would edit the original tree.\n\
         ///\n\
         /// ```\n\
         /// use clingox::ast::{self, Ast, AstType, Attribute, Visitor, walk};\n\
         /// use clingox::Result;\n\
         ///\n\
         /// /// Drops the first body literal of every rule.\n\
         /// struct DropFirst;\n\
         ///\n\
         /// impl Visitor for DropFirst {\n\
         ///     fn visit_rule(&mut self, node: &Ast) -> Result<Ast> {\n\
         ///         let walked = walk(self, node)?;\n\
         ///         let edited = if walked.ptr_eq(node) { walked.copy()? } else { walked };\n\
         ///         if edited.ast_array_len(Attribute::Body)? > 0 {\n\
         ///             edited.delete_ast_at(Attribute::Body, 0)?;\n\
         ///         }\n\
         ///         Ok(edited)\n\
         ///     }\n\
         /// }\n\
         ///\n\
         /// let mut rules = Vec::new();\n\
         /// ast::parse_string(\"h :- a, b.\", |node| {\n\
         ///     if node.ast_type() == AstType::Rule {\n\
         ///         rules.push(node);\n\
         ///     }\n\
         ///     Ok(())\n\
         /// })?;\n\
         /// let rewritten = DropFirst.visit(&rules[0])?;\n\
         /// assert_eq!(rewritten.to_string(), \"h :- b.\");\n\
         /// assert_eq!(rules[0].to_string(), \"h :- a; b.\");\n\
         /// # Ok::<(), clingox::Error>(())\n\
         /// ```\n\
         pub trait Visitor {\n\
         \x20   /// Dispatches on `node.ast_type()` to the matching `visit_*` method.\n\
         \x20   ///\n\
         \x20   /// # Errors\n\
         \x20   ///\n\
         \x20   /// Whatever the method it calls returns.\n\
         \x20   fn visit(&mut self, node: &Ast) -> Result<Ast> {\n\
         \x20       match node.ast_type() {\n",
    );
    for constructor in &tables.constructors {
        let _ = writeln!(
            out,
            "            AstType::{} => self.visit_{}(node),",
            camel(&constructor.name),
            constructor.name
        );
    }
    out.push_str(
        "            AstType::Other(_) => self.visit_other(node),\n\
         \x20       }\n\
         \x20   }\n\n",
    );
    for constructor in &tables.constructors {
        let _ = writeln!(
            out,
            "    /// Visits a [`AstType::{}`] node. Defaults to [`walk`].\n\
             \x20   ///\n\
             \x20   /// # Errors\n\
             \x20   ///\n\
             \x20   /// As [`Visitor::visit`].\n\
             \x20   fn visit_{}(&mut self, node: &Ast) -> Result<Ast> {{\n\
             \x20       walk(self, node)\n\
             \x20   }}\n",
            camel(&constructor.name),
            constructor.name
        );
    }
    out.push_str(
        "    /// Visits a node of a type this build does not know ([`AstType::Other`]).\n\
         \x20   /// Defaults to returning the node unchanged.\n\
         \x20   ///\n\
         \x20   /// # Errors\n\
         \x20   ///\n\
         \x20   /// As [`Visitor::visit`].\n\
         \x20   fn visit_other(&mut self, node: &Ast) -> Result<Ast> {\n\
         \x20       Ok(node.clone())\n\
         \x20   }\n\
         }\n\n",
    );

    out.push_str(
        "/// Visits the children of `node` through `visitor` and rebuilds `node` when\n\
         /// any of them changed.\n\
         ///\n\
         /// For each child attribute of the node's type, in constructor order:\n\
         /// an `ast` attribute is visited, an `optional_ast` is skipped when it is\n\
         /// `None` and visited otherwise, and every element of an `ast_array` is\n\
         /// visited in index order, one replacement per element (the length cannot\n\
         /// change here). Other attributes (`location`, names, symbols, numbers,\n\
         /// strings) are never visited.\n\
         ///\n\
         /// If no child changed, the result is a clone of `node`, so it is\n\
         /// [`Ast::ptr_eq`] to it and nothing is allocated. Otherwise the result is\n\
         /// `node.copy()` with only the changed children replaced: unchanged\n\
         /// children and siblings stay shared with the original, and every other\n\
         /// attribute, the location included, is kept. The original is never\n\
         /// modified.\n\
         ///\n\
         /// An override can call `walk` before or after its own edits. See\n\
         /// [`Visitor`] for how to delete or insert array elements.\n\
         ///\n\
         /// # Stack use\n\
         ///\n\
         /// `walk` recurses once per level of the tree, through\n\
         /// [`Visitor::visit`], like pyclingo's `Transformer`, and has no depth\n\
         /// limit of its own. A tree deep enough to exhaust the thread's stack\n\
         /// overflows it. Printing, comparing and dropping such a tree recurse in\n\
         /// clingo the same way, so a tree that clingo itself can print on a\n\
         /// thread can also be walked on it; run a visitor over very deep trees on\n\
         /// a thread with a large stack.\n\
         ///\n\
         /// # Errors\n\
         ///\n\
         /// The first error any `visit_*` method, setter or `copy` reports, which\n\
         /// is returned unchanged.\n\
         pub fn walk<V: Visitor + ?Sized>(visitor: &mut V, node: &Ast) -> Result<Ast> {\n\
         \x20   let mut rebuilt: Option<Ast> = None;\n\
         \x20   for &(attribute, kind) in child_attributes(node.ast_type()) {\n\
         \x20       match kind {\n\
         \x20           AttributeType::Ast => {\n\
         \x20               let child = node.ast(attribute)?;\n\
         \x20               let visited = visitor.visit(&child)?;\n\
         \x20               if !visited.ptr_eq(&child) {\n\
         \x20                   copy_of(&mut rebuilt, node)?.set_ast_fresh(attribute, &visited)?;\n\
         \x20               }\n\
         \x20           }\n\
         \x20           AttributeType::OptionalAst => {\n\
         \x20               if let Some(child) = node.optional_ast(attribute)? {\n\
         \x20                   let visited = visitor.visit(&child)?;\n\
         \x20                   if !visited.ptr_eq(&child) {\n\
         \x20                       copy_of(&mut rebuilt, node)?\n\
         \x20                           .set_optional_ast_fresh(attribute, &visited)?;\n\
         \x20                   }\n\
         \x20               }\n\
         \x20           }\n\
         \x20           AttributeType::AstArray => {\n\
         \x20               for index in 0..node.ast_array_len(attribute)? {\n\
         \x20                   let child = node.ast_at(attribute, index)?;\n\
         \x20                   let visited = visitor.visit(&child)?;\n\
         \x20                   if !visited.ptr_eq(&child) {\n\
         \x20                       copy_of(&mut rebuilt, node)?\n\
         \x20                           .set_ast_at_fresh(attribute, index, &visited)?;\n\
         \x20                   }\n\
         \x20               }\n\
         \x20           }\n\
         \x20           _ => {}\n\
         \x20       }\n\
         \x20   }\n\
         \x20   Ok(rebuilt.unwrap_or_else(|| node.clone()))\n\
         }\n\n\
         /// The private copy `walk` edits: made on the first change, and a handle to\n\
         /// the same node afterwards.\n\
         ///\n\
         /// This is why `walk` may use the setters that skip the cycle check: the copy\n\
         /// is new, and only `walk` holds a handle to it until `walk` returns. A\n\
         /// replacement a visitor returns was made before the copy could be reached,\n\
         /// so it cannot reach the copy, and adding it below the copy cannot close a\n\
         /// cycle. The original tree is only read.\n\
         fn copy_of(rebuilt: &mut Option<Ast>, node: &Ast) -> Result<Ast> {\n\
         \x20   if let Some(copy) = rebuilt {\n\
         \x20       return Ok(copy.clone());\n\
         \x20   }\n\
         \x20   let copy = node.copy()?;\n\
         \x20   *rebuilt = Some(copy.clone());\n\
         \x20   Ok(copy)\n\
         }\n",
    );
}

// ---------------------------------------------------------------------------
// The raw layer
// ---------------------------------------------------------------------------

fn raw_source(tables: &Tables) -> String {
    let mut out = String::new();
    out.push_str(
        "//! The one call of the variadic `clingo_ast_build`, with the C argument\n\
         //! types of every node type taken from clingo's constructor table.\n\
         //!\n\
         //! Generated by `cargo xtask ast-codegen`.\n\n\
         #![allow(\n\
         \x20   clippy::too_many_lines,\n\
         \x20   reason = \"one arm per node type, generated from the table\"\n\
         )]\n\n\
         use clingox_sys as ffi;\n\n\
         use super::ast::Prepared;\n\
         use super::c_int_of;\n\
         use crate::ast::AstType;\n\n\
         /// Builds a node of type `kind` from `args`, the C values of the arguments\n\
         /// the constructor table lists for it, in order.\n\
         ///\n\
         /// `args` must have been prepared from arguments of exactly the kinds the\n\
         /// table lists (the safe constructors are generated from the same table);\n\
         /// its accessors panic otherwise, before any pointer is read.\n\
         pub(super) fn build(\n\
         \x20   kind: AstType,\n\
         \x20   args: &Prepared,\n\
         \x20   out: &mut *mut ffi::clingo_ast_t,\n\
         ) -> bool {\n\
         \x20   unsafe {\n\
         \x20       match kind {\n",
    );
    for constructor in &tables.constructors {
        let mut list = vec![
            format!("c_int_of(ffi::clingo_ast_type_{})", constructor.name),
            "out".to_owned(),
        ];
        for (index, argument) in constructor.arguments.iter().enumerate() {
            match argument.kind {
                NUMBER => list.push(format!("args.number({index})")),
                SYMBOL => list.push(format!("args.symbol({index})")),
                LOCATION => list.push(format!("args.location({index})")),
                STRING => list.push(format!("args.string({index})")),
                AST => list.push(format!("args.ast({index})")),
                OPTIONAL_AST => list.push(format!("args.optional_ast({index})")),
                STRING_ARRAY => {
                    list.push(format!("args.string_array({index})"));
                    list.push(format!("args.string_array_len({index})"));
                }
                AST_ARRAY => {
                    list.push(format!("args.ast_array({index})"));
                    list.push(format!("args.ast_array_len({index})"));
                }
                other => unreachable!("assert_tables rejected the attribute type {other}"),
            }
        }
        let _ = writeln!(
            out,
            "            AstType::{} => ffi::clingo_ast_build({}),",
            camel(&constructor.name),
            list.join(", ")
        );
    }
    out.push_str(
        "            AstType::Other(_) => unreachable!(\"`ast_build` rejects an unknown node type first\"),\n\
         \x20       }\n\
         \x20   }\n\
         }\n",
    );
    out
}

/// The `SAFETY` comment of the one unsafe block, one entry per line.
const RAW_SAFETY: [&str; 11] = [
    "SAFETY: `clingo_ast_build` reads its variadic arguments in the order and",
    "with the C types of the constructor table entry for `kind` (control.cc,",
    "`clingo_ast_build`): `int` for a number, `clingo_symbol_t` for a symbol,",
    "`const clingo_location_t *`, `const char *`, `clingo_ast_t *` (null for",
    "an absent optional node), and a pointer plus a `size_t` for an array.",
    "Each arm below passes exactly the table's arguments for its node type,",
    "in the table's order and with those types, because this file is",
    "generated from the table. Every pointer comes from `args`, which owns",
    "the C strings and arrays and borrows the nodes, and outlives the call;",
    "the accessors panic on a mismatched kind before a pointer is read. `out`",
    "is a valid out-pointer.",
];

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

/// Parses and unparses `source`, so the bytes do not depend on `rustfmt`.
fn unparse(source: &str) -> Result<String> {
    let file =
        syn::parse_file(source).map_err(|e| format!("the generated source does not parse: {e}"))?;
    Ok(prettyplease::unparse(&file))
}

fn finish(source: &str) -> Result<String> {
    Ok(format!("{HEADER}{}", unparse(source)?))
}

/// As [`finish`], and restores the `SAFETY` comment that `prettyplease` would
/// drop with every other plain comment.
fn finish_raw(source: &str) -> Result<String> {
    let text = unparse(source)?;
    let marker = "    unsafe {\n";
    let Some(at) = text.find(marker) else {
        return Err("the generated raw source lost its unsafe block".into());
    };
    let mut with_comment = String::with_capacity(text.len() + 1024);
    with_comment.push_str(&text[..at]);
    for line in RAW_SAFETY {
        with_comment.push_str("    // ");
        with_comment.push_str(line);
        with_comment.push('\n');
    }
    with_comment.push_str(&text[at..]);
    Ok(format!("{HEADER}{with_comment}"))
}
